export const DECKS = {
  personajesPeliculas: {
    id: 'personajesPeliculas',
    name: 'Personajes de Películas',
    words: [
      'Harry Potter',
      'Darth Vader',
      'Katniss Everdeen',
      'Elsa',
      'Iron Man',
      'Jack Sparrow',
      'Sherlock Holmes',
      'Hermione Granger',
      'Luke Skywalker',
      'Wonder Woman',
      'Batman',
      'Gandalf',
      'Forrest Gump',
      'E.T.',
      'Mickey Mouse',
      'Buzz Lightyear',
      'Shrek',
      'Donkey',
      'Fiona',
      'Puss in Boots',
      'Anna',
      'Olaf',
      'Will Turner',
      'Elizabeth Swann',
      'Neo',
      'Trinity',
      'Morpheus',
      'Indiana Jones',
      'Lara Croft',
      'Tony Stark',
      'Steve Rogers',
      'Natasha Romanoff',
      'Peter Parker',
      'Bruce Banner',
      'Thanos',
      'Loki',
      'Groot',
      'Rocket Raccoon',
      'Deadpool',
      'Wolverine',
      'Yoda',
      'Obi-Wan Kenobi',
      'Princess Leia',
      'Han Solo',
      'Chewbacca',
      'R2-D2',
      'C-3PO',
      'Joker',
      'Harley Quinn',
      'Catwoman',
      'Terminator',
      'Ellen Ripley',
      'John Wick',
      'James Bond',
      'Jason Bourne',
    ],
  },
  animales: {
    id: 'animales',
    name: 'Animales',
    words: [
      'León',
      'Pingüino',
      'Jirafa',
      'Delfín',
      'Ornitorrinco',
      'Tiranosaurio Rex',
      'Elefante',
      'Tigre',
      'Panda',
      'Águila',
      'Ballena',
      'Cocodrilo',
      'Oso',
      'Zebra',
      'Hipopótamo',
      'Rinoceronte',
      'Guepardo',
      'Leopardo',
      'Lobo',
      'Zorro',
      'Lince',
      'Puma',
      'Jaguar',
      'Oso Polar',
      'Oso Grizzly',
      'Koala',
      'Canguro',
      'Cisne',
      'Flamenco',
      'Avestruz',
      'Pelícano',
      'Tucán',
      'Guacamayo',
      'Loro',
      'Búho',
      'Halcón',
      'Cóndor',
      'Pavo Real',
      'Iguana',
      'Camaleón',
      'Tortuga',
      'Serpiente',
      'Boa',
      'Cobra',
      'Rana',
      'Tiburón',
      'Raya',
      'Pulpo',
      'Calamar',
      'Medusa',
      'Cangrejo',
      'Mariposa',
      'Abeja',
      'Araña',
      'Escorpión',
      'Gusano',
      'Caracol',
    ],
  },
  celebridades: {
    id: 'celebridades',
    name: 'Celebridades',
    words: [
      'Shakira',
      'Lionel Messi',
      'Frida Kahlo',
      'Elon Musk',
      'Taylor Swift',
      'Will Smith',
      'Leonardo DiCaprio',
      'Beyoncé',
      'Cristiano Ronaldo',
      'Oprah Winfrey',
      'Brad Pitt',
      'Emma Watson',
      'Tom Hanks',
      'Jennifer Lawrence',
      'Ed Sheeran',
      'Ariana Grande',
      'Justin Bieber',
      'Billie Eilish',
      'The Weeknd',
      'Drake',
      'Post Malone',
      'Dua Lipa',
      'Adele',
      'Bruno Mars',
      'Rihanna',
      'Katy Perry',
      'Lady Gaga',
      'Madonna',
      'Michael Jackson',
      'The Beatles',
      'Queen',
      'David Bowie',
      'Eminem',
      'Jay-Z',
      'Kanye West',
      'Harry Styles',
      'BTS',
      'Blackpink',
      'Bad Bunny',
      'J Balvin',
      'Rosalía',
      'Selena Gomez',
      'Miley Cyrus',
      'Demi Lovato',
      'Olivia Rodrigo',
      'Lana Del Rey',
      'Coldplay',
      'Arctic Monkeys',
      'Imagine Dragons',
      'Green Day',
      'Linkin Park',
    ],
  },
  objetosCasa: {
    id: 'objetosCasa',
    name: 'Cosas de Casa',
    words: [
      'Microondas',
      'Sofá',
      'Lavadora',
      'Tostadora',
      'Mando a distancia',
      'Cepillo de dientes',
      'Almohada',
      'Espejo',
      'Televisor',
      'Refrigerador',
      'Cama',
      'Mesa',
      'Silla',
      'Lámpara',
      'Ventilador',
      'Aire Acondicionado',
      'Estufa',
      'Horno',
      'Lavavajillas',
      'Licuadora',
      'Batidora',
      'Cafetera',
      'Hervidor',
      'Tetera',
      'Taza',
      'Vaso',
      'Plato',
      'Cuchara',
      'Tenedor',
      'Cuchillo',
      'Sartén',
      'Olla',
      'Tabla de Cortar',
      'Rallador',
      'Espátula',
      'Cuchara de Madera',
      'Tijeras',
      'Abrelatas',
      'Abrebotellas',
      'Trapo',
      'Estropajo',
      'Escoba',
      'Recogedor',
      'Fregona',
      'Aspiradora',
      'Detergente',
      'Jabón',
      'Champú',
      'Crema',
      'Desodorante',
      'Perfume',
      'Cepillo',
      'Peine',
      'Toalla',
      'Cortina',
      'Percha',
      'Cesto',
      'Cajón',
      'Estantería',
      'Armario',
      'Sillón',
      'Mantel',
      'Servilleta',
      'Salero',
      'Pimentero',
      'Azucarero',
      'Aceitera',
      'Vinagrera',
      'Ventilador',
      'Aire Acondicionado',
      'Estufa',
      'Horno',
      'Lavavajillas',
      'Licuadora',
      'Batidora',
      'Cafetera',
      'Hervidor',
      'Tetera',
      'Taza',
      'Vaso',
      'Plato',
      'Cuchara',
      'Tenedor',
      'Cuchillo',
      'Sartén',
      'Olla',
      'Tabla de Cortar',
      'Abridor',
      'Pelador',
      'Colador',
      'Rallador',
      'Espátula',
      'Cuchara de Madera',
      'Pinzas',
      'Tijeras',
      'Abrelatas',
      'Abrebotellas',
      'Sacacorchos',
      'Trapo',
      'Estropajo',
      'Escoba',
      'Recogedor',
      'Fregona',
      'Aspiradora',
      'Limpiavidrios',
      'Bayeta',
      'Desinfectante',
      'Detergente',
      'Suavizante',
      'Jabón',
      'Champú',
      'Acondicionador',
      'Crema',
      'Desodorante',
      'Perfume',
      'Maquillaje',
      'Pintalabios',
      'Máscara de Pestañas',
      'Base',
      'Polvo',
      'Rubor',
      'Sombra de Ojos',
      'Delineador',
      'Cepillo de Maquillaje',
      'Esponja',
      'Pinzas',
      'Tijeras de Uñas',
      'Cortauñas',
      'Limauñas',
      'Cera',
      'Gel',
      'Laca',
      'Plancha',
      'Secador',
      'Tenacillas',
      'Rizador',
      'Peine',
      'Cepillo',
      'Horquillas',
      'Gomas',
      'Pasadores',
      'Cola',
      'Esponja',
      'Toalla',
      'Alfombra de Baño',
      'Cortina de Ducha',
      'Jabonera',
      'Portalámpara',
      'Espejo de Aumento',
      'Percha',
      'Gancho',
      'Cesto',
      'Canasta',
      'Cajón',
      'Estantería',
      'Armario',
      'Cómoda',
      'Mesa de Noche',
      'Escritorio',
      'Sillón',
      'Puff',
      'Taburete',
      'Banco',
      'Mecedora',
      'Hamaca',
      'Butaca',
      'Diván',
      'Futón',
      'Colchón',
      'Sommier',
      'Base',
      'Cabecero',
      'Almohada',
      'Funda',
      'Sábana',
      'Manta',
      'Edredón',
      'Colcha',
      'Funda Nórdica',
      'Cobertor',
      'Mantel',
      'Individual',
      'Servilleta',
      'Delantal',
      'Guante de Cocina',
      'Agarrador',
      'Posavasos',
      'Salero',
      'Pimentero',
      'Azucarero',
      'Aceitera',
      'Vinagrera',
      'Molinillo',
      'Espumadera',
      'Cazo',
      'Cacerola',
      'Cazuela',
      'Wok',
      'Plancha',
      'Sandwichera',
      'Wafflera',
      'Máquina de Pan',
      'Máquina de Café',
      'Tostadora',
      'Hervidor',
      'Exprimidor',
      'Licuadora',
      'Batidora',
      'Procesador',
      'Robots',
      'Picadora',
      'Rallador Eléctrico',
      'Ablandador',
      'Vaporera',
      'Olla a Presión',
      'Olla Lenta',
      'Freidora',
      'Horno de Convección',
      'Grill',
      'Plancha Eléctrica',
      'Sandwichera',
      'Wafflera',
      'Máquina de Pan',
      'Máquina de Café',
      'Tostadora',
      'Hervidor',
      'Exprimidor',
      'Licuadora',
      'Batidora',
      'Procesador',
      'Robots',
      'Picadora',
      'Rallador Eléctrico',
      'Ablandador',
      'Vaporera',
      'Olla a Presión',
      'Olla Lenta',
      'Freidora',
      'Horno de Convección',
      'Grill',
      'Plancha Eléctrica',
      'Máquina de Helados',
      'Máquina de Palomitas',
      'Máquina de Algodón',
      'Máquina de Churros',
      'Máquina de Crepes',
      'Máquina de Donuts',
      'Máquina de Pretzels',
      'Máquina de Bagels',
      'Máquina de Muffins',
      'Máquina de Cupcakes',
      'Máquina de Brownies',
      'Máquina de Galletas',
      'Máquina de Pasteles',
      'Máquina de Tartas',
      'Máquina de Flanes',
      'Máquina de Natillas',
      'Máquina de Pudding',
      'Máquina de Mousse',
      'Máquina de Soufflé',
      'Máquina de Merengue',
      'Máquina de Nata',
      'Máquina de Crema',
      'Máquina de Salsa',
      'Máquina de Mayonesa',
      'Máquina de Ketchup',
      'Máquina de Mostaza',
      'Máquina de Mermelada',
      'Máquina de Compota',
      'Máquina de Puré',
      'Máquina de Papilla',
      'Máquina de Zumo',
      'Máquina de Smoothie',
      'Máquina de Batido',
      'Máquina de Milkshake',
      'Máquina de Frappé',
      'Máquina de Granizado',
      'Máquina de Sorbete',
      'Máquina de Hielo',
      'Máquina de Cubitos',
      'Máquina de Agua',
      'Máquina de Soda',
      'Máquina de Refrescos',
      'Máquina de Cerveza',
      'Máquina de Vino',
      'Máquina de Champán',
      'Máquina de Cócteles',
      'Máquina de Mojitos',
      'Máquina de Margaritas',
      'Máquina de Daiquiris',
      'Máquina de Piña Colada',
      'Máquina de Sangría',
      'Máquina de Ponche',
      'Máquina de Grog',
      'Máquina de Hot Toddy',
      'Máquina de Irish Coffee',
      'Máquina de Café con Leche',
      'Máquina de Cappuccino',
      'Máquina de Latte',
      'Máquina de Mocha',
      'Máquina de Macchiato',
      'Máquina de Espresso',
      'Máquina de Americano',
      'Máquina de Cortado',
      'Máquina de Carajillo',
      'Máquina de Bombón',
      'Máquina de Café Bombón',
      'Máquina de Café con Hielo',
      'Máquina de Frappuccino',
      'Máquina de Café Helado',
      'Máquina de Café Granizado',
      'Máquina de Café con Leche Helado',
      'Máquina de Té',
      'Máquina de Té Verde',
      'Máquina de Té Negro',
      'Máquina de Té Rojo',
      'Máquina de Té Blanco',
      'Máquina de Té Azul',
      'Máquina de Té de Hierbas',
      'Máquina de Té de Frutas',
      'Máquina de Té de Especias',
      'Máquina de Té Chai',
      'Máquina de Té Matcha',
      'Máquina de Té Earl Grey',
      'Máquina de Té English Breakfast',
      'Máquina de Té Darjeeling',
      'Máquina de Té Assam',
      'Máquina de Té Ceylon',
      'Máquina de Té Lapsang Souchong',
      'Máquina de Té Jasmine',
      'Máquina de Té Chamomile',
      'Máquina de Té Peppermint',
      'Máquina de Té Rooibos',
      'Máquina de Té Honeybush',
      'Máquina de Té Yerba Mate',
      'Máquina de Té Pu-erh',
      'Máquina de Té Oolong',
      'Máquina de Té Sencha',
      'Máquina de Té Gyokuro',
      'Máquina de Té Genmaicha',
      'Máquina de Té Hojicha',
      'Máquina de Té Kukicha',
      'Máquina de Té Bancha',
      'Máquina de Té Konacha',
      'Máquina de Té Mecha',
      'Máquina de Té Tamaryokucha',
      'Máquina de Té Kamairicha',
      'Máquina de Té Kabusecha',
      'Máquina de Té Tencha',
      'Máquina de Té Kokeicha',
      'Máquina de Té Aracha',
      'Máquina de Té Shincha',
      'Máquina de Té Ichibancha',
      'Máquina de Té Nibancha',
      'Máquina de Té Sanbancha',
      'Máquina de Té Yonbancha',
      'Máquina de Té Gobancha',
      'Máquina de Té Rokubancha',
      'Máquina de Té Shichibancha',
      'Máquina de Té Hachibancha',
      'Máquina de Té Kyubancha',
      'Máquina de Té Jubancha',
    ],
  },
  superheroes: {
    id: 'superheroes',
    name: 'Superhéroes',
    words: [
      'Superman',
      'Spider-Man',
      'Wonder Woman',
      'Hulk',
      'Capitán América',
      'Thor',
      'Black Widow',
      'Iron Man',
      'Batman',
      'Flash',
      'Aquaman',
      'Wolverine',
      'Deadpool',
      'Supergirl',
    ],
  },
};

export const DEFAULT_TIME_LIMIT = 60; // segundos
export const TILT_THRESHOLD = 0.7; // umbral para detectar inclinación
export const TIME_OPTIONS = [60, 90, 120]; // opciones de tiempo en segundos

