// Fragmentos de palabras para generar títulos de películas absurdas
export const FRAGMENTOS_TITULOS = {
  // Sustantivos
  sustantivos: [
    'Aguacate', 'Tostada', 'Gnomo', 'Semáforo', 'Cactus', 'Calcetín',
    'Aspiradora', 'Filósofo', 'Paloma', 'Silla', 'Wi-Fi', 'Post-it',
    'Clip', 'Botella', 'Patito', 'Goma', 'Lápiz', 'Taza',
    'Cuchara', 'Almohada', 'Cepillo', 'Espejo', 'Candado', 'Cordón',
    'Bolígrafo', 'Libreta', 'Carpeta', 'Grapa', 'Sobre', 'Cartera',
    'Pantalón', 'Camisa', 'Zapato', 'Gorra', 'Bufanda', 'Guante',
    'Reloj', 'Llave', 'Moneda', 'Billete', 'Cajón', 'Caja',
    'Saco', 'Bolsa', 'Mochila', 'Maleta', 'Equipaje', 'Teclado',
    'Ratón', 'Pantalla', 'Auriculares', 'Micrófono', 'Cámara', 'Dron',
    'Robot', 'Androide', 'Alienígena', 'Extraterrestre', 'UFO', 'Nave',
    'Cohete', 'Satélite', 'Planeta', 'Estrella', 'Cometa', 'Asteroide',
    'Galaxia', 'Nebulosa', 'Agujero Negro', 'Quasar', 'Pulsar', 'Supernova',
    'Dinosaurio', 'Mamut', 'Dragón', 'Unicornio', 'Fénix', 'Pegaso',
    'Grifo', 'Quimera', 'Hidra', 'Basilisco', 'Kraken', 'Leviathán',
    'Troll', 'Elfo', 'Hada', 'Duende', 'Gigante', 'Enano',
    'Bruja', 'Mago', 'Hechicero', 'Necromante', 'Paladín', 'Guerrero',
    'Caballero', 'Princesa', 'Rey', 'Reina', 'Emperador', 'Emperatriz',
    'Vikingo', 'Samurái', 'Ninja', 'Pirata', 'Corsario', 'Bucanero',
    'Explorador', 'Aventurero', 'Arqueólogo', 'Antropólogo', 'Biólogo', 'Químico',
    'Físico', 'Matemático', 'Astrónomo', 'Astrofísico', 'Cosmólogo', 'Geólogo',
    'Psicólogo', 'Psiquiatra', 'Neurologo', 'Neurocirujano', 'Cardiólogo', 'Oncólogo',
    'Chef', 'Pastelero', 'Sommelier', 'Barista', 'Mesero', 'Camarero',
    'DJ', 'Músico', 'Cantante', 'Baterista', 'Guitarrista', 'Pianista',
    'Actor', 'Actriz', 'Director', 'Productor', 'Guionista', 'Editor',
    'Fotógrafo', 'Cineasta', 'Documentalista', 'Animador', 'Diseñador', 'Ilustrador',
    'Escritor', 'Poeta', 'Novelista', 'Crítico', 'Periodista', 'Reportero',
    'Piloto', 'Copiloto', 'Azafata', 'Controlador', 'Mecánico', 'Ingeniero',
    'Arquitecto', 'Ingeniero Civil', 'Topógrafo', 'Urbanista', 'Diseñador', 'Decorador',
    'Programador', 'Desarrollador', 'Hacker', 'Administrador', 'Analista', 'Consultor',
    'Abogado', 'Juez', 'Fiscal', 'Detective', 'Policía', 'Guardia',
    'Bombero', 'Paramédico', 'Médico', 'Enfermero', 'Veterinario', 'Dentista',
    'Profesor', 'Maestro', 'Estudiante', 'Investigador', 'Científico', 'Tecnólogo',
    'Atleta', 'Deportista', 'Entrenador', 'Arbitro', 'Jugador', 'Fanático',
    'Artista', 'Pintor', 'Escultor', 'Grabador', 'Grabador', 'Ceramista',
    'Jardinero', 'Agricultor', 'Ganadero', 'Pescador', 'Cazador', 'Recolector',
    'Carpintero', 'Herrero', 'Albañil', 'Fontanero', 'Electricista', 'Soldador',
    'Conductor', 'Taxista', 'Chófer', 'Repartidor', 'Mensajero', 'Correo',
    'Comerciante', 'Vendedor', 'Comprador', 'Cliente', 'Consumidor', 'Usuario',
    'Empleado', 'Trabajador', 'Obrero', 'Ejecutivo', 'Gerente', 'Director',
    'Empresario', 'Emprendedor', 'Inversionista', 'Banquero', 'Economista', 'Contador',
    'Turista', 'Viajero', 'Explorador', 'Aventurero', 'Nómada', 'Erudito',
    'Monje', 'Sacerdote', 'Pastor', 'Rabino', 'Imán', 'Gurú',
    'Filosofo', 'Teólogo', 'Historiador', 'Geógrafo', 'Sociólogo', 'Politólogo',
    'Politico', 'Senador', 'Diputado', 'Alcalde', 'Gobernador', 'Presidente',
    'Soldado', 'Marinero', 'Aviador', 'Submarinista', 'Paracaidista', 'Comando',
    'Espía', 'Agente', 'Informante', 'Infiltrado', 'Soplón', 'Traidor',
    'Héroe', 'Villano', 'Antihéroe', 'Protagonista', 'Antagonista', 'Secundario',
    'Extras', 'Figurante', 'Especialista', 'Doble', 'Sustituto', 'Suplente',
    'Mascota', 'Animal', 'Perro', 'Gato', 'Pájaro', 'Pez',
    'Hamster', 'Conejo', 'Cobaya', 'Ratón', 'Hámster', 'Hurón',
    'Iguana', 'Serpiente', 'Tortuga', 'Lagarto', 'Gecko', 'Camaleón',
    'Araña', 'Escorpión', 'Ciempiés', 'Milpiés', 'Cucaracha', 'Hormiga',
    'Abeja', 'Avispa', 'Mariposa', 'Polilla', 'Libélula', 'Mantis',
    'Grillo', 'Saltamontes', 'Cigarra', 'Chinche', 'Pulgón', 'Cochinilla',
    'Caracol', 'Babosa', 'Ostra', 'Mejillón', 'Almeja', 'Erizo',
    'Estrella de Mar', 'Medusa', 'Pulpo', 'Calamar', 'Sepia', 'Nautilo',
    'Cangrejo', 'Langosta', 'Bogavante', 'Gamba', 'Camarón', 'Langostino',
    'Pez Globo', 'Pez Espada', 'Pez Martillo', 'Tiburón', 'Raya', 'Manta',
    'Ballena', 'Delfín', 'Foca', 'León Marino', 'Morsa', 'Nutria',
    'Oso', 'Oso Polar', 'Oso Panda', 'Oso Pardo', 'Oso Grizzly', 'Oso Negro',
    'León', 'Tigre', 'Leopardo', 'Jaguar', 'Puma', 'Guepardo',
    'Lobo', 'Coyote', 'Zorro', 'Chacal', 'Hiena', 'Licaón',
    'Elefante', 'Rinoceronte', 'Hipopótamo', 'Jirafa', 'Cebrada', 'Ñu',
    'Antílope', 'Gacela', 'Impala', 'Búfalo', 'Bisonte', 'Alce',
    'Ciervo', 'Venado', 'Reno', 'Caribú', 'Muflón', 'Cabra',
    'Oveja', 'Cordero', 'Cerdo', 'Jabalí', 'Vaca', 'Toro',
    'Caballo', 'Yegua', 'Potro', 'Pony', 'Burro', 'Mula',
    'Camello', 'Dromedario', 'Llama', 'Alpaca', 'Vicuña', 'Guanaco',
    'Canguro', 'Ualabí', 'Koala', 'Wombat', 'Diablo de Tasmania', 'Ornitorrinco',
    'Equidna', 'Kiwi', 'Emú', 'Avestruz', 'Ñandú', 'Casuario',
    'Pingüino', 'Cormorán', 'Pelícano', 'Albatros', 'Gaviota', 'Gaviotín',
    'Flamenco', 'Grulla', 'Garza', 'Cigüeña', 'Ibis', 'Espátula',
    'Cisne', 'Ganso', 'Pato', 'Ánade', 'Pato Silbador', 'Pato Mandarín',
    'Búho', 'Lechuza', 'Mochuelo', 'Autillo', 'Cárabo', 'Búho Nival',
    'Águila', 'Halcón', 'Aguilucho', 'Milano', 'Ratón', 'Cernícalo',
    'Buitre', 'Quebrantahuesos', 'Alimoche', 'Carroñero', 'Condor', 'Zopilote',
    'Cuervo', 'Grajilla', 'Corneja', 'Urraca', 'Arrendajo', 'Graja',
    'Gorrión', 'Pardillo', 'Verderón', 'Jilguero', 'Canario', 'Pinzón',
    'Mirlo', 'Estornino', 'Tordo', 'Zorzal', 'Petirrojo', 'Ruiseñor',
    'Colibrí', 'Chupaflor', 'Picaflor', 'Tucusito', 'Esmeralda', 'Amazilia',
    'Tucán', 'Pájaro Carpintero', 'Trepador', 'Herrerillo', 'Carbonero', 'Herrerillo',
    'Loro', 'Guacamayo', 'Cacatúa', 'Periquito', 'Agapornis', 'Ninfas',
    'Cotorra', 'Papagayo', 'Yaco', 'Eclectus', 'Loro Gris', 'Loro Real',
    'Ara', 'Guacamayo Azul', 'Guacamayo Rojo', 'Guacamayo Verde', 'Guacamayo Amarillo', 'Guacamayo Escarlata',
    'Cacatúa Blanca', 'Cacatúa Negra', 'Cacatúa Rosa', 'Cacatúa de Galah', 'Cacatúa de las Molucas', 'Cacatúa de Goffin',
    'Periquito Australiano', 'Periquito Inglés', 'Periquito de Bourke', 'Periquito Elegante', 'Periquito de Cola Larga', 'Periquito de Cola Corta',
    'Agapornis Fischer', 'Agapornis Personata', 'Agapornis Roseicollis', 'Agapornis Nigrigenis', 'Agapornis Lilianae', 'Agapornis Taranta',
    'Ninfas', 'Cockatiel', 'Carolina', 'Cacatúa Ninfa', 'Ninfas Gris', 'Ninfas Perlada',
    'Canario', 'Canario Silvestre', 'Canario Doméstico', 'Canario Amarillo', 'Canario Rojo', 'Canario Blanco',
    'Jilguero', 'Jilguero Europeo', 'Jilguero Americano', 'Jilguero de Pico Negro', 'Jilguero de Pico Rojo', 'Jilguero de Cabeza Negra',
    'Pinzón', 'Pinzón Vulgar', 'Pinzón Real', 'Pinzón de Cabeza Roja', 'Pinzón de Cabeza Amarilla', 'Pinzón de Cabeza Azul',
    'Mirlo', 'Mirlo Común', 'Mirlo de Agua', 'Mirlo Capiblanco', 'Mirlo de Pico Amarillo', 'Mirlo de Pico Rojo',
    'Estornino', 'Estornino Pinto', 'Estornino Negro', 'Estornino Purpúreo', 'Estornino de Cola Larga', 'Estornino de Cola Corta',
    'Tordo', 'Tordo Común', 'Tordo de Cabeza Negra', 'Tordo de Cabeza Roja', 'Tordo de Cabeza Amarilla', 'Tordo de Cabeza Azul',
    'Zorzal', 'Zorzal Común', 'Zorzal Real', 'Zorzal de Cabeza Roja', 'Zorzal de Cabeza Amarilla', 'Zorzal de Cabeza Azul',
    'Petirrojo', 'Petirrojo Europeo', 'Petirrojo Americano', 'Petirrojo de Cabeza Negra', 'Petirrojo de Cabeza Roja', 'Petirrojo de Cabeza Amarilla',
    'Ruiseñor', 'Ruiseñor Común', 'Ruiseñor del Japón', 'Ruiseñor de Cabeza Negra', 'Ruiseñor de Cabeza Roja', 'Ruiseñor de Cabeza Amarilla',
    'Colibrí', 'Colibrí Esmeralda', 'Colibrí Amazilia', 'Colibrí de Cabeza Negra', 'Colibrí de Cabeza Roja', 'Colibrí de Cabeza Amarilla',
    'Chupaflor', 'Chupaflor Esmeralda', 'Chupaflor Amazilia', 'Chupaflor de Cabeza Negra', 'Chupaflor de Cabeza Roja', 'Chupaflor de Cabeza Amarilla',
    'Picaflor', 'Picaflor Esmeralda', 'Picaflor Amazilia', 'Picaflor de Cabeza Negra', 'Picaflor de Cabeza Roja', 'Picaflor de Cabeza Amarilla',
    'Tucusito', 'Tucusito Esmeralda', 'Tucusito Amazilia', 'Tucusito de Cabeza Negra', 'Tucusito de Cabeza Roja', 'Tucusito de Cabeza Amarilla',
    'Esmeralda', 'Esmeralda Común', 'Esmeralda de Cabeza Negra', 'Esmeralda de Cabeza Roja', 'Esmeralda de Cabeza Amarilla', 'Esmeralda de Cabeza Azul',
    'Amazilia', 'Amazilia Común', 'Amazilia de Cabeza Negra', 'Amazilia de Cabeza Roja', 'Amazilia de Cabeza Amarilla', 'Amazilia de Cabeza Azul',
    'Tucán', 'Tucán Toco', 'Tucán de Pico Rojo', 'Tucán de Pico Amarillo', 'Tucán de Pico Verde', 'Tucán de Pico Azul',
    'Pájaro Carpintero', 'Pájaro Carpintero Pico Rojo', 'Pájaro Carpintero Pico Amarillo', 'Pájaro Carpintero Pico Verde', 'Pájaro Carpintero Pico Azul', 'Pájaro Carpintero Pico Negro',
    'Trepador', 'Trepador Azul', 'Trepador Rojo', 'Trepador Amarillo', 'Trepador Verde', 'Trepador Negro',
    'Herrerillo', 'Herrerillo Común', 'Herrerillo Azul', 'Herrerillo Rojo', 'Herrerillo Amarillo', 'Herrerillo Verde',
    'Carbonero', 'Carbonero Común', 'Carbonero Azul', 'Carbonero Rojo', 'Carbonero Amarillo', 'Carbonero Verde',
    'Herrerillo', 'Herrerillo Común', 'Herrerillo Azul', 'Herrerillo Rojo', 'Herrerillo Amarillo', 'Herrerillo Verde',
    'Loro', 'Loro Gris', 'Loro Real', 'Loro de Cabeza Negra', 'Loro de Cabeza Roja', 'Loro de Cabeza Amarilla',
    'Guacamayo', 'Guacamayo Azul', 'Guacamayo Rojo', 'Guacamayo Verde', 'Guacamayo Amarillo', 'Guacamayo Escarlata',
    'Cacatúa', 'Cacatúa Blanca', 'Cacatúa Negra', 'Cacatúa Rosa', 'Cacatúa de Galah', 'Cacatúa de las Molucas',
    'Periquito', 'Periquito Australiano', 'Periquito Inglés', 'Periquito de Bourke', 'Periquito Elegante', 'Periquito de Cola Larga',
    'Agapornis', 'Agapornis Fischer', 'Agapornis Personata', 'Agapornis Roseicollis', 'Agapornis Nigrigenis', 'Agapornis Lilianae',
    'Ninfas', 'Ninfas Gris', 'Ninfas Perlada', 'Ninfas de Cabeza Negra', 'Ninfas de Cabeza Roja', 'Ninfas de Cabeza Amarilla',
    'Cotorra', 'Cotorra Argentina', 'Cotorra de Cabeza Negra', 'Cotorra de Cabeza Roja', 'Cotorra de Cabeza Amarilla', 'Cotorra de Cabeza Azul',
    'Papagayo', 'Papagayo de Cabeza Negra', 'Papagayo de Cabeza Roja', 'Papagayo de Cabeza Amarilla', 'Papagayo de Cabeza Azul', 'Papagayo de Cabeza Verde',
    'Yaco', 'Yaco de Cabeza Negra', 'Yaco de Cabeza Roja', 'Yaco de Cabeza Amarilla', 'Yaco de Cabeza Azul', 'Yaco de Cabeza Verde',
    'Eclectus', 'Eclectus Macho', 'Eclectus Hembra', 'Eclectus de Cabeza Negra', 'Eclectus de Cabeza Roja', 'Eclectus de Cabeza Amarilla',
    'Loro Gris', 'Loro Gris Africano', 'Loro Gris de Cabeza Negra', 'Loro Gris de Cabeza Roja', 'Loro Gris de Cabeza Amarilla', 'Loro Gris de Cabeza Azul',
    'Loro Real', 'Loro Real de Cabeza Negra', 'Loro Real de Cabeza Roja', 'Loro Real de Cabeza Amarilla', 'Loro Real de Cabeza Azul', 'Loro Real de Cabeza Verde',
    'Ara', 'Ara Azul', 'Ara Roja', 'Ara Verde', 'Ara Amarilla', 'Ara Escarlata',
    'Guacamayo Azul', 'Guacamayo Azul y Amarillo', 'Guacamayo Azul y Rojo', 'Guacamayo Azul y Verde', 'Guacamayo Azul y Negro', 'Guacamayo Azul y Blanco',
    'Guacamayo Rojo', 'Guacamayo Rojo y Amarillo', 'Guacamayo Rojo y Verde', 'Guacamayo Rojo y Azul', 'Guacamayo Rojo y Negro', 'Guacamayo Rojo y Blanco',
    'Guacamayo Verde', 'Guacamayo Verde y Amarillo', 'Guacamayo Verde y Rojo', 'Guacamayo Verde y Azul', 'Guacamayo Verde y Negro', 'Guacamayo Verde y Blanco',
    'Guacamayo Amarillo', 'Guacamayo Amarillo y Rojo', 'Guacamayo Amarillo y Verde', 'Guacamayo Amarillo y Azul', 'Guacamayo Amarillo y Negro', 'Guacamayo Amarillo y Blanco',
    'Guacamayo Escarlata', 'Guacamayo Escarlata y Amarillo', 'Guacamayo Escarlata y Rojo', 'Guacamayo Escarlata y Verde', 'Guacamayo Escarlata y Azul', 'Guacamayo Escarlata y Negro',
    'Cacatúa Blanca', 'Cacatúa Blanca de Cabeza Negra', 'Cacatúa Blanca de Cabeza Roja', 'Cacatúa Blanca de Cabeza Amarilla', 'Cacatúa Blanca de Cabeza Azul', 'Cacatúa Blanca de Cabeza Verde',
    'Cacatúa Negra', 'Cacatúa Negra de Cabeza Blanca', 'Cacatúa Negra de Cabeza Roja', 'Cacatúa Negra de Cabeza Amarilla', 'Cacatúa Negra de Cabeza Azul', 'Cacatúa Negra de Cabeza Verde',
    'Cacatúa Rosa', 'Cacatúa Rosa de Cabeza Negra', 'Cacatúa Rosa de Cabeza Roja', 'Cacatúa Rosa de Cabeza Amarilla', 'Cacatúa Rosa de Cabeza Azul', 'Cacatúa Rosa de Cabeza Verde',
    'Cacatúa de Galah', 'Cacatúa de Galah de Cabeza Negra', 'Cacatúa de Galah de Cabeza Roja', 'Cacatúa de Galah de Cabeza Amarilla', 'Cacatúa de Galah de Cabeza Azul', 'Cacatúa de Galah de Cabeza Verde',
    'Cacatúa de las Molucas', 'Cacatúa de las Molucas de Cabeza Negra', 'Cacatúa de las Molucas de Cabeza Roja', 'Cacatúa de las Molucas de Cabeza Amarilla', 'Cacatúa de las Molucas de Cabeza Azul', 'Cacatúa de las Molucas de Cabeza Verde',
    'Cacatúa de Goffin', 'Cacatúa de Goffin de Cabeza Negra', 'Cacatúa de Goffin de Cabeza Roja', 'Cacatúa de Goffin de Cabeza Amarilla', 'Cacatúa de Goffin de Cabeza Azul', 'Cacatúa de Goffin de Cabeza Verde',
    'Periquito Australiano', 'Periquito Australiano de Cabeza Negra', 'Periquito Australiano de Cabeza Roja', 'Periquito Australiano de Cabeza Amarilla', 'Periquito Australiano de Cabeza Azul', 'Periquito Australiano de Cabeza Verde',
    'Periquito Inglés', 'Periquito Inglés de Cabeza Negra', 'Periquito Inglés de Cabeza Roja', 'Periquito Inglés de Cabeza Amarilla', 'Periquito Inglés de Cabeza Azul', 'Periquito Inglés de Cabeza Verde',
    'Periquito de Bourke', 'Periquito de Bourke de Cabeza Negra', 'Periquito de Bourke de Cabeza Roja', 'Periquito de Bourke de Cabeza Amarilla', 'Periquito de Bourke de Cabeza Azul', 'Periquito de Bourke de Cabeza Verde',
    'Periquito Elegante', 'Periquito Elegante de Cabeza Negra', 'Periquito Elegante de Cabeza Roja', 'Periquito Elegante de Cabeza Amarilla', 'Periquito Elegante de Cabeza Azul', 'Periquito Elegante de Cabeza Verde',
    'Periquito de Cola Larga', 'Periquito de Cola Larga de Cabeza Negra', 'Periquito de Cola Larga de Cabeza Roja', 'Periquito de Cola Larga de Cabeza Amarilla', 'Periquito de Cola Larga de Cabeza Azul', 'Periquito de Cola Larga de Cabeza Verde',
    'Periquito de Cola Corta', 'Periquito de Cola Corta de Cabeza Negra', 'Periquito de Cola Corta de Cabeza Roja', 'Periquito de Cola Corta de Cabeza Amarilla', 'Periquito de Cola Corta de Cabeza Azul', 'Periquito de Cola Corta de Cabeza Verde',
    'Agapornis Fischer', 'Agapornis Fischer de Cabeza Negra', 'Agapornis Fischer de Cabeza Roja', 'Agapornis Fischer de Cabeza Amarilla', 'Agapornis Fischer de Cabeza Azul', 'Agapornis Fischer de Cabeza Verde',
    'Agapornis Personata', 'Agapornis Personata de Cabeza Negra', 'Agapornis Personata de Cabeza Roja', 'Agapornis Personata de Cabeza Amarilla', 'Agapornis Personata de Cabeza Azul', 'Agapornis Personata de Cabeza Verde',
    'Agapornis Roseicollis', 'Agapornis Roseicollis de Cabeza Negra', 'Agapornis Roseicollis de Cabeza Roja', 'Agapornis Roseicollis de Cabeza Amarilla', 'Agapornis Roseicollis de Cabeza Azul', 'Agapornis Roseicollis de Cabeza Verde',
    'Agapornis Nigrigenis', 'Agapornis Nigrigenis de Cabeza Negra', 'Agapornis Nigrigenis de Cabeza Roja', 'Agapornis Nigrigenis de Cabeza Amarilla', 'Agapornis Nigrigenis de Cabeza Azul', 'Agapornis Nigrigenis de Cabeza Verde',
    'Agapornis Lilianae', 'Agapornis Lilianae de Cabeza Negra', 'Agapornis Lilianae de Cabeza Roja', 'Agapornis Lilianae de Cabeza Amarilla', 'Agapornis Lilianae de Cabeza Azul', 'Agapornis Lilianae de Cabeza Verde',
    'Agapornis Taranta', 'Agapornis Taranta de Cabeza Negra', 'Agapornis Taranta de Cabeza Roja', 'Agapornis Taranta de Cabeza Amarilla', 'Agapornis Taranta de Cabeza Azul', 'Agapornis Taranta de Cabeza Verde',
    'Ninfas', 'Ninfas Gris', 'Ninfas Perlada', 'Ninfas de Cabeza Negra', 'Ninfas de Cabeza Roja', 'Ninfas de Cabeza Amarilla',
    'Cockatiel', 'Cockatiel Gris', 'Cockatiel Perlada', 'Cockatiel de Cabeza Negra', 'Cockatiel de Cabeza Roja', 'Cockatiel de Cabeza Amarilla',
    'Carolina', 'Carolina Gris', 'Carolina Perlada', 'Carolina de Cabeza Negra', 'Carolina de Cabeza Roja', 'Carolina de Cabeza Amarilla',
    'Cacatúa Ninfa', 'Cacatúa Ninfa Gris', 'Cacatúa Ninfa Perlada', 'Cacatúa Ninfa de Cabeza Negra', 'Cacatúa Ninfa de Cabeza Roja', 'Cacatúa Ninfa de Cabeza Amarilla',
    'Ninfas Gris', 'Ninfas Gris Perlada', 'Ninfas Gris de Cabeza Negra', 'Ninfas Gris de Cabeza Roja', 'Ninfas Gris de Cabeza Amarilla', 'Ninfas Gris de Cabeza Azul',
    'Ninfas Perlada', 'Ninfas Perlada de Cabeza Negra', 'Ninfas Perlada de Cabeza Roja', 'Ninfas Perlada de Cabeza Amarilla', 'Ninfas Perlada de Cabeza Azul', 'Ninfas Perlada de Cabeza Verde',
    'Ninfas de Cabeza Negra', 'Ninfas de Cabeza Negra Perlada', 'Ninfas de Cabeza Negra de Cabeza Roja', 'Ninfas de Cabeza Negra de Cabeza Amarilla', 'Ninfas de Cabeza Negra de Cabeza Azul', 'Ninfas de Cabeza Negra de Cabeza Verde',
    'Ninfas de Cabeza Roja', 'Ninfas de Cabeza Roja Perlada', 'Ninfas de Cabeza Roja de Cabeza Negra', 'Ninfas de Cabeza Roja de Cabeza Amarilla', 'Ninfas de Cabeza Roja de Cabeza Azul', 'Ninfas de Cabeza Roja de Cabeza Verde',
    'Ninfas de Cabeza Amarilla', 'Ninfas de Cabeza Amarilla Perlada', 'Ninfas de Cabeza Amarilla de Cabeza Negra', 'Ninfas de Cabeza Amarilla de Cabeza Roja', 'Ninfas de Cabeza Amarilla de Cabeza Azul', 'Ninfas de Cabeza Amarilla de Cabeza Verde',
    'Cotorra', 'Cotorra Argentina', 'Cotorra de Cabeza Negra', 'Cotorra de Cabeza Roja', 'Cotorra de Cabeza Amarilla', 'Cotorra de Cabeza Azul',
    'Papagayo', 'Papagayo de Cabeza Negra', 'Papagayo de Cabeza Roja', 'Papagayo de Cabeza Amarilla', 'Papagayo de Cabeza Azul', 'Papagayo de Cabeza Verde',
    'Yaco', 'Yaco de Cabeza Negra', 'Yaco de Cabeza Roja', 'Yaco de Cabeza Amarilla', 'Yaco de Cabeza Azul', 'Yaco de Cabeza Verde',
    'Eclectus', 'Eclectus Macho', 'Eclectus Hembra', 'Eclectus de Cabeza Negra', 'Eclectus de Cabeza Roja', 'Eclectus de Cabeza Amarilla',
    'Loro Gris', 'Loro Gris Africano', 'Loro Gris de Cabeza Negra', 'Loro Gris de Cabeza Roja', 'Loro Gris de Cabeza Amarilla', 'Loro Gris de Cabeza Azul',
    'Loro Real', 'Loro Real de Cabeza Negra', 'Loro Real de Cabeza Roja', 'Loro Real de Cabeza Amarilla', 'Loro Real de Cabeza Azul', 'Loro Real de Cabeza Verde',
  ],
  
  // Adjetivos
  adjetivos: [
    'Vengador', 'Cuántico', 'Ninja', 'Melancólico', 'Solitario',
    'Perdido', 'Intergaláctico', 'Mutante', 'Descontento', 'Embrujado',
    'Peligroso', 'Último', 'Invisible', 'Gigante', 'Minúsculo',
    'Brillante', 'Opaco', 'Transparente', 'Mágico', 'Misterioso',
    'Hipnotizante', 'Electrónico', 'Digital', 'Analógico', 'Virtual',
    'Real', 'Falso', 'Auténtico', 'Original', 'Copiado',
    'Antiguo', 'Moderno', 'Futurista', 'Retro', 'Clásico', 'Nuevo',
    'Viejo', 'Joven', 'Maduro', 'Inmaduro', 'Sabio', 'Ignorante',
    'Épico', 'Legendario', 'Mítico', 'Cósmico', 'Extraterrestre',
    'Dimensional', 'Temporal', 'Atemporal', 'Eterno', 'Infinito',
    'Absurdo', 'Surrealista', 'Onírico', 'Psicodélico', 'Alucinante',
    'Fenomenal', 'Extraordinario', 'Increíble', 'Imposible', 'Improbable',
    'Desquiciado', 'Loco', 'Demente', 'Genial', 'Brillante',
    'Oscuro', 'Tenebroso', 'Lúgubre', 'Siniestro', 'Maldito',
    'Sagrado', 'Divino', 'Celestial', 'Angélico', 'Demoníaco',
    'Robótico', 'Cibernético', 'Mecánico', 'Automático', 'Programado',
    'Orgánico', 'Biológico', 'Natural', 'Artificial', 'Sintético',
    'Explosivo', 'Dinámico', 'Energético', 'Vibrante', 'Radiante',
    'Sombrio', 'Luminoso', 'Resplandeciente', 'Fosforescente', 'Bioluminiscente',
    'Gélido', 'Ardiente', 'Glacial', 'Tórrido', 'Tropical',
    'Acuático', 'Submarino', 'Aéreo', 'Volador', 'Espacial',
    'Terrestre', 'Marciano', 'Venusiano', 'Jupiteriano', 'Saturniano',
    'Nebuloso', 'Estelar', 'Galáctico', 'Universal', 'Multiversal',
  ],
  
  // Verbos
  verbos: [
    'Rebelión', 'Ataque', 'Misterio', 'Crónicas', 'Aventura',
    'Viaje', 'Búsqueda', 'Escape', 'Persecución', 'Descubrimiento',
    'Invasión', 'Defensa', 'Rescate', 'Salvación', 'Destrucción',
    'Construcción', 'Creación', 'Transformación', 'Evolución', 'Revolución',
    'Invención', 'Exploración', 'Conquista', 'Victoria',
    'Derrota', 'Triunfo', 'Fracaso', 'Éxito', 'Logro', 'Hazaña',
    'Odisea', 'Épica', 'Leyenda', 'Saga', 'Saga Épica',
    'Encuentro', 'Conflicto', 'Batalla', 'Guerra', 'Paz',
    'Resurrección', 'Renacimiento', 'Regreso', 'Retorno', 'Desaparición',
    'Apocalipsis', 'Revelación', 'Profecía', 'Predicción', 'Advertencia',
    'Misión', 'Operación', 'Proyecto', 'Plan', 'Conspiración',
    'Ascenso', 'Caída', 'Elevación', 'Descenso', 'Ascenso',
    'Trascendencia', 'Metamorfosis', 'Mutación', 'Alteración', 'Cambio',
    'Revelación', 'Secretos', 'Misterios', 'Enigmas', 'Puzzles',
    'Legado', 'Herencia', 'Tradición', 'Futuro', 'Pasado',
    'Origen', 'Destino', 'Propósito', 'Significado', 'Sentido',
  ],
  
  // Lugares
  lugares: [
    'Marte', 'Espacio-Tiempo', 'Nueva York', 'Hong Kong', 'París',
    'Londres', 'Tokio', 'Moscú', 'Roma', 'Madrid', 'Barcelona',
    'Berlín', 'Ámsterdam', 'Viena', 'Praga', 'Estocolmo', 'Copenhague',
    'Oslo', 'Helsinki', 'Dublín', 'Lisboa', 'Atenas', 'El Cairo',
    'Dubái', 'Singapur', 'Sídney', 'Melbourne', 'Toronto', 'Montreal',
    'México', 'Buenos Aires', 'Santiago', 'Lima', 'Bogotá', 'Caracas',
    'Río de Janeiro', 'São Paulo', 'Brasilia', 'La Habana', 'San Juan',
    'Júpiter', 'Venus', 'Saturno', 'Neptuno', 'Plutón',
    'La Luna', 'Europa', 'Titán', 'Ganímedes', 'Io',
    'Alpha Centauri', 'Proxima Centauri', 'Sirio', 'Vega', 'Betelgeuse',
    'La Nebulosa de Orión', 'La Vía Láctea', 'Andrómeda', 'La Nube de Magallanes',
    'El Cinturón de Kuiper', 'La Nube de Oort', 'El Agujero Negro Central',
    'Dimensiones Paralelas', 'El Multiverso', 'El Vacío Cuántico',
    'El Inframundo', 'El Cielo', 'El Purgatorio', 'El Limbo', 'El Paraíso',
    'El Desierto del Sáhara', 'El Amazonas', 'El Himalaya', 'El Ártico', 'La Antártida',
    'El Triángulo de las Bermudas', 'El Área 51', 'Stonehenge', 'Las Pirámides',
    'El Monte Everest', 'La Fosa de las Marianas', 'El Gran Cañón', 'El Salto del Ángel',
  ],
  
  // Objetos/Conceptos adicionales
  objetos: [
    'Pijama', 'Ketchup', 'Mostaza', 'Mayonesa', 'Salsa',
    'Mermelada', 'Mantequilla', 'Azúcar', 'Sal',
    'Pimienta', 'Canela', 'Vainilla', 'Chocolate', 'Caramelo',
    'Chicle', 'Gominola', 'Galleta', 'Pastel', 'Tarta',
    'Tortilla', 'Pan', 'Leche', 'Agua', 'Jugo',
    'Refresco', 'Café', 'Té', 'Infusión', 'Bebida',
    'Energía', 'Materia', 'Antimateria', 'Plasma', 'Cristal',
    'Oro', 'Plata', 'Diamante', 'Rubí', 'Esmeralda',
    'Fuego', 'Hielo', 'Viento', 'Tierra', 'Éter',
    'Luz', 'Oscuridad', 'Sombra', 'Brillo', 'Resplandor',
    'Sueño', 'Pesadilla', 'Ilusión', 'Realidad', 'Fantasía',
    'Tiempo', 'Espacio', 'Gravitación', 'Magnetismo', 'Electricidad',
    'Sonido', 'Silencio', 'Música', 'Armonía', 'Caos',
    'Orden', 'Desorden', 'Equilibrio', 'Desequilibrio', 'Estabilidad',
  ],
  
  // Preposiciones y conectores comunes
  conectores: [
    'de', 'del', 'de la', 'en', 'con', 'sin',
    'por', 'para', 'sobre', 'bajo', 'entre', 'hacia',
    'desde', 'hasta', 'durante', 'mediante', 'según', 'contra',
  ],
};

// Ejemplos predefinidos de títulos (del documento Markdown)
export const TITULOS_PREDEFINIDOS = [
  'El Aguacate Vengador y la Tostada Cuántica',
  'Mi Vecino es un Gnomo Ninja en Pijama',
  'La Rebelión de los Semáforos Melancólicos',
  'Sinfonía para un Cactus Solitario en Marte',
  'Los Calcetines Perdidos del Espacio-Tiempo',
  'Ataque de la Aspiradora Intergaláctica con Sentimientos',
  'El Filósofo que Hablaba con las Palomas Mutantes',
  'Crónicas de una Silla de Oficina Descontenta',
  'El Misterio del Wi-Fi Embrujado',
  'La Peligrosa Aventura del Último Post-it del Mundo',
];

