export const CHARACTERS = [
  'Un superhéroe que le teme a las alturas',
  'Un fantasma que busca trabajo de oficina',
  'Un T-Rex tratando de conseguir un trabajo como recepcionista',
  'Un vampiro con miedo a la sangre que busca un trabajo de turno de noche',
  'Un robot que acaba de descubrir las emociones y es demasiado honesto',
  'Un dragón que intenta ocultar su identidad para ser contable',
  'Un mago que perdió su varita y necesita trabajo en tecnología',
  'Un pirata que quiere ser profesor de matemáticas',
  'Un alienígena tratando de pasar por humano en recursos humanos',
  'Un lobo que quiere trabajar como guardia de seguridad',
  'Un payaso que busca trabajo serio en un banco',
  'Un zombie que quiere ser chef en un restaurante vegano',
  'Un unicornio que necesita trabajo como programador',
  'Un monstruo del lago Ness buscando trabajo remoto',
  'Un elfo que quiere ser vendedor de seguros',
  'Un ogro que busca trabajo como peluquero',
  'Un hada que quiere ser ingeniero de construcción',
  'Un duende que necesita trabajo como bibliotecario',
  'Un hombre lobo que busca trabajo como veterinario',
  'Un gato que habla y quiere ser psicólogo',
  'Un pato que quiere ser piloto de avión',
  'Un pingüino que busca trabajo en una agencia de viajes',
  'Un pulpo que quiere ser contador (tiene 8 brazos para trabajar)',
  'Un pez que quiere ser bombero',
  'Un elefante que busca trabajo como portero de hotel',
  'Un león que quiere ser recepcionista de hotel',
  'Un oso que busca trabajo como guardabosques',
  'Un zorro que quiere ser detective privado',
  'Un conejo que busca trabajo como atleta profesional',
  'Un cerdo que quiere ser chef gourmet',
  'Un mímico que quiere trabajar en una tienda de muebles',
  'Un yeti que busca trabajo como repartidor en la montaña',
  'Un genio que quiere ser empleado de atención al cliente',
  'Un sirena que busca trabajo como salvavidas en piscina',
  'Un centauro que quiere ser mensajero de bicicletas',
  'Un grifo que busca trabajo como guardia de aeropuerto',
  'Un fénix que quiere ser chef especializado en parrillas',
  'Un cíclope que busca trabajo como oculista',
  'Un medusa que quiere ser peluquera profesional',
  'Un minotauro que busca trabajo como guía de laberintos',
  'Un basilisco que quiere ser entrenador de mascotas',
  'Un quimera que busca trabajo como diseñador gráfico',
  'Un hidra que quiere ser conserje de múltiples edificios',
  'Un cerbero que busca trabajo como guardia de seguridad',
  'Un esfinge que quiere ser profesor de historia',
  'Un kraken que busca trabajo como masajista de múltiples extremidades',
  'Un pegaso que quiere ser repartidor de comida rápida',
  'Un gorgona que busca trabajo como maquilladora profesional',
  'Un titán que quiere ser arquitecto de rascacielos',
  'Un dragón de hielo que busca trabajo como conservador de museo',
  'Un demonio que quiere ser psicólogo especializado en terapia de ira',
  'Un ángel que busca trabajo como paracaidista instructor',
  'Un esqueleto que quiere ser modelo de ropa',
  'Un licántropo que busca trabajo como guardia nocturno',
  'Un vampiro vegetariano que quiere ser nutricionista',
  'Un zombi consciente que busca trabajo como embalsamador',
  'Un fantasma que quiere ser animador de eventos',
  'Un brujo que busca trabajo como farmacéutico',
  'Un hechicero que quiere ser desarrollador de software mágico',
  'Un druida que busca trabajo como guardaparque',
  'Un bardo que quiere ser youtuber de música',
  'Un paladín que busca trabajo como entrenador personal',
  'Un nigromante que quiere ser director de funeraria',
  'Un alquimista que busca trabajo como químico de laboratorio',
  'Un samurái que quiere ser consultor de negocios',
  'Un ninja que busca trabajo como agente de seguridad privada',
  'Un vikingo que quiere ser capitán de barco turístico',
  'Un caballero que busca trabajo como guardia de honor',
  'Un gladiador que quiere ser entrenador de boxeo',
  'Un explorador que busca trabajo como guía turístico',
  'Un inventor que quiere ser ingeniero de innovación',
  'Un científico loco que busca trabajo como investigador',
  'Un artista que quiere ser crítico de arte',
  'Un escritor que busca trabajo como redactor creativo',
  'Un músico que quiere ser DJ de radio',
  'Un actor que busca trabajo como doble de riesgo',
  'Un bailarín que quiere ser coreógrafo de teatro',
  'Un chef que busca trabajo como crítico gastronómico',
  'Un médico que quiere ser especialista en medicina alternativa',
  'Un abogado que busca trabajo como mediador de conflictos',
  'Un profesor que quiere ser tutor online',
  'Un ingeniero que busca trabajo como consultor técnico',
  'Un arquitecto que quiere ser diseñador de interiores',
  'Un diseñador que busca trabajo como estilista de moda',
  'Un fotógrafo que quiere ser influencer de redes sociales',
  'Un periodista que busca trabajo como reportero de campo',
  'Un traductor que quiere ser intérprete simultáneo',
  'Un contador que busca trabajo como auditor financiero',
];

export const CHARACTER_THEMES = {
  fantasy: [
    'Un superhéroe que le teme a las alturas',
    'Un fantasma que busca trabajo de oficina',
    'Un vampiro con miedo a la sangre que busca un trabajo de turno de noche',
    'Un dragón que intenta ocultar su identidad para ser contable',
    'Un mago que perdió su varita y necesita trabajo en tecnología',
    'Un elfo que quiere ser vendedor de seguros',
    'Un ogro que busca trabajo como peluquero',
    'Un hada que quiere ser ingeniero de construcción',
    'Un duende que necesita trabajo como bibliotecario',
    'Un hombre lobo que busca trabajo como veterinario',
    'Un mímico que quiere trabajar en una tienda de muebles',
    'Un yeti que busca trabajo como repartidor en la montaña',
    'Un genio que quiere ser empleado de atención al cliente',
    'Un sirena que busca trabajo como salvavidas en piscina',
    'Un centauro que quiere ser mensajero de bicicletas',
    'Un grifo que busca trabajo como guardia de aeropuerto',
    'Un fénix que quiere ser chef especializado en parrillas',
    'Un cíclope que busca trabajo como oculista',
    'Un medusa que quiere ser peluquera profesional',
    'Un minotauro que busca trabajo como guía de laberintos',
    'Un basilisco que quiere ser entrenador de mascotas',
    'Un quimera que busca trabajo como diseñador gráfico',
    'Un hidra que quiere ser conserje de múltiples edificios',
    'Un cerbero que busca trabajo como guardia de seguridad',
    'Un esfinge que quiere ser profesor de historia',
    'Un kraken que busca trabajo como masajista de múltiples extremidades',
    'Un pegaso que quiere ser repartidor de comida rápida',
    'Un gorgona que busca trabajo como maquilladora profesional',
    'Un titán que quiere ser arquitecto de rascacielos',
    'Un dragón de hielo que busca trabajo como conservador de museo',
    'Un demonio que quiere ser psicólogo especializado en terapia de ira',
    'Un ángel que busca trabajo como paracaidista instructor',
    'Un esqueleto que quiere ser modelo de ropa',
    'Un licántropo que busca trabajo como guardia nocturno',
    'Un vampiro vegetariano que quiere ser nutricionista',
    'Un zombi consciente que busca trabajo como embalsamador',
    'Un fantasma que quiere ser animador de eventos',
    'Un brujo que busca trabajo como farmacéutico',
    'Un hechicero que quiere ser desarrollador de software mágico',
    'Un druida que busca trabajo como guardaparque',
    'Un bardo que quiere ser youtuber de música',
    'Un paladín que busca trabajo como entrenador personal',
    'Un nigromante que quiere ser director de funeraria',
    'Un alquimista que busca trabajo como químico de laboratorio',
    'Un samurái que quiere ser consultor de negocios',
    'Un ninja que busca trabajo como agente de seguridad privada',
    'Un vikingo que quiere ser capitán de barco turístico',
    'Un caballero que busca trabajo como guardia de honor',
    'Un gladiador que quiere ser entrenador de boxeo',
  ],
  animals: [
    'Un T-Rex tratando de conseguir un trabajo como recepcionista',
    'Un lobo que quiere trabajar como guardia de seguridad',
    'Un gato que habla y quiere ser psicólogo',
    'Un pato que quiere ser piloto de avión',
    'Un pingüino que busca trabajo en una agencia de viajes',
    'Un pulpo que quiere ser contador (tiene 8 brazos para trabajar)',
    'Un pez que quiere ser bombero',
    'Un elefante que busca trabajo como portero de hotel',
    'Un león que quiere ser recepcionista de hotel',
    'Un oso que busca trabajo como guardabosques',
    'Un zorro que quiere ser detective privado',
    'Un conejo que busca trabajo como atleta profesional',
    'Un cerdo que quiere ser chef gourmet',
  ],
  scifi: [
    'Un robot que acaba de descubrir las emociones y es demasiado honesto',
    'Un alienígena tratando de pasar por humano en recursos humanos',
    'Un unicornio que necesita trabajo como programador',
    'Un monstruo del lago Ness buscando trabajo remoto',
  ],
};

export const getRandomCharacter = (theme = null) => {
  let characterList = CHARACTERS;
  
  if (theme && CHARACTER_THEMES[theme]) {
    characterList = CHARACTER_THEMES[theme];
  }
  
  const randomIndex = Math.floor(Math.random() * characterList.length);
  return characterList[randomIndex];
};

