export const INTERVIEW_QUESTIONS = [
  '¿Cuál diría que es su mayor debilidad?',
  '¿Cómo maneja las críticas en el trabajo?',
  '¿Dónde te ves en cinco años?',
  '¿Por qué quiere trabajar en esta empresa?',
  '¿Cuál es su mayor fortaleza?',
  '¿Cómo maneja el estrés y la presión?',
  'Descríbame una situación difícil que haya enfrentado y cómo la resolvió',
  '¿Qué lo motiva en el trabajo?',
  '¿Cómo trabaja en equipo?',
  '¿Cuál es su mayor logro profesional?',
  '¿Por qué dejó su trabajo anterior?',
  '¿Qué sabe sobre nuestra empresa?',
  '¿Cómo se ve a sí mismo en tres años?',
  '¿Cuál es su expectativa salarial?',
  '¿Tiene alguna pregunta para nosotros?',
  '¿Cómo mantiene un equilibrio entre trabajo y vida personal?',
  'Descríbame un proyecto del que esté especialmente orgulloso',
  '¿Cómo maneja los plazos ajustados?',
  '¿Qué habilidades trae a este puesto?',
  '¿Cómo se adapta a los cambios?',
  'Descríbame un conflicto que haya tenido con un compañero y cómo lo resolvió',
  '¿Qué tipo de ambiente de trabajo prefiere?',
  '¿Cómo se mantiene actualizado en su campo?',
  'Descríbame un momento en que tuvo que tomar una decisión difícil',
  '¿Qué hace cuando no está seguro de cómo completar una tarea?',
  '¿Cómo describe su estilo de trabajo?',
  '¿Qué lo hace diferente de otros candidatos?',
  '¿Cómo maneja la retroalimentación negativa?',
  '¿Cuál es su filosofía de trabajo?',
  '¿Cómo se mantiene organizado?',
  'Descríbame un error que haya cometido y qué aprendió de él',
  '¿Qué espera lograr en su primer mes?',
  '¿Cómo prioriza sus tareas?',
  '¿Qué le gusta hacer fuera del trabajo?',
  '¿Cómo maneja situaciones de multitarea?',
  '¿Qué lo hizo decidirse por esta carrera?',
  'Descríbame un momento en que tuvo que ser creativo para resolver un problema',
  '¿Cómo se comunica con personas difíciles?',
  '¿Qué haría si no estuviera de acuerdo con su jefe?',
  '¿Cómo maneja los proyectos a largo plazo?',
  '¿Qué lo mantiene motivado durante los días difíciles?',
  '¿Cómo se asegura de cumplir con los objetivos?',
  'Descríbame un logro de equipo del que esté orgulloso',
  '¿Cómo equilibra las necesidades del cliente con los recursos disponibles?',
  '¿Qué estrategias usa para aprender cosas nuevas?',
  '¿Cómo maneja la incertidumbre en el trabajo?',
  '¿Qué hace cuando se siente abrumado?',
  'Descríbame una situación en que tuvo que liderar sin autoridad formal',
  '¿Cómo se asegura de que todos en el equipo estén alineados?',
  '¿Qué opina sobre trabajar horas extra?',
  '¿Cómo maneja la competencia con compañeros?',
  '¿Qué lo hace sentir más realizado en el trabajo?',
  'Descríbame un momento en que tuvo que negociar algo importante',
  '¿Cómo se adapta a nuevas tecnologías?',
  '¿Qué haría si un cliente estuviera insatisfecho?',
  '¿Cómo maneja la información confidencial?',
  'Descríbame una vez que tuvo que trabajar bajo presión extrema',
  '¿Qué opina sobre el trabajo remoto?',
  '¿Cómo se mantiene productivo durante el día?',
  '¿Qué haría si descubriera que un compañero está haciendo algo incorrecto?',
  'Descríbame cómo manejaría un proyecto que está atrasado',
  '¿Cómo se asegura de entender las expectativas?',
  '¿Qué lo hace sentir nervioso en el trabajo?',
  '¿Cómo celebra sus logros?',
  'Descríbame una situación en que tuvo que adaptarse rápidamente',
  '¿Qué aprendió de su último trabajo?',
  '¿Cómo maneja la retroalimentación de múltiples fuentes?',
  '¿Qué haría si tuviera que elegir entre calidad y velocidad?',
  'Descríbame cómo manejaría un conflicto entre dos miembros del equipo',
  '¿Cómo se mantiene actualizado con las tendencias de la industria?',
  '¿Qué opina sobre la diversidad en el lugar de trabajo?',
  '¿Cómo maneja las expectativas no realistas?',
  'Descríbame un momento en que tuvo que decir "no" a una solicitud',
  '¿Qué lo hace sentir más cómodo en un ambiente laboral?',
  '¿Cómo maneja las interrupciones constantes?',
  '¿Qué estrategias usa para construir relaciones profesionales?',
  'Descríbame cómo lidiaría con un jefe microgerente',
  '¿Qué haría si tuviera que trabajar con alguien con quien no se lleva bien?',
  '¿Cómo se asegura de que todos los stakeholders estén informados?',
  '¿Qué opina sobre la innovación en el trabajo?',
  'Descríbame una vez que tuvo que defender una decisión impopular',
  '¿Cómo maneja la transición entre diferentes proyectos?',
  '¿Qué lo motiva más: el reconocimiento o la satisfacción personal?',
  'Descríbame cómo manejaría un proyecto que está sobre el presupuesto',
  '¿Cómo se asegura de mantener la calidad mientras aumenta la velocidad?',
  '¿Qué haría si tuviera que trabajar en un área fuera de su expertise?',
  'Descríbame cómo manejaría un cliente particularmente difícil',
  '¿Cómo se mantiene enfocado en los objetivos a largo plazo?',
  '¿Qué opina sobre la colaboración interdepartamental?',
  'Descríbame una situación en que tuvo que improvisar una solución',
  '¿Cómo maneja la presión de cumplir con múltiples deadlines?',
  '¿Qué haría si tuviera que elegir entre dos oportunidades igualmente atractivas?',
];

export const DEPARTMENT_QUESTIONS = {
  rrhh: [
    '¿Cómo manejaría una situación de conflicto entre empleados?',
    '¿Qué estrategias usaría para mejorar el ambiente laboral?',
    '¿Cómo evaluaría el desempeño de un empleado?',
  ],
  marketing: [
    '¿Cómo desarrollaría una campaña publicitaria?',
    '¿Qué estrategias usaría para aumentar la visibilidad de la marca?',
    '¿Cómo mediría el éxito de una campaña?',
  ],
  ingenieria: [
    '¿Cómo abordaría un problema técnico complejo?',
    '¿Qué metodologías de desarrollo prefiere?',
    '¿Cómo se asegura de que su código sea mantenible?',
  ],
};

export const getRandomQuestion = (department = null) => {
  if (department && DEPARTMENT_QUESTIONS[department]) {
    const deptQuestions = DEPARTMENT_QUESTIONS[department];
    const randomIndex = Math.floor(Math.random() * deptQuestions.length);
    return deptQuestions[randomIndex];
  }
  
  const randomIndex = Math.floor(Math.random() * INTERVIEW_QUESTIONS.length);
  return INTERVIEW_QUESTIONS[randomIndex];
};

