export const SITUATIONS = [
  'Cambiaste el azúcar por la sal en la cafetera de la oficina',
  'Te comiste la última porción de tarta de cumpleaños y culpaste a tu hermano pequeño',
  'Usaste el champú más caro de tu pareja para lavar al perro',
  'Le dijiste a un turista una dirección completamente equivocada a propósito',
  'Rompiste la silla favorita de tu abuela y la escondiste en el armario',
  'Te hiciste pasar por un famoso en una cafetería para conseguir una bebida gratis',
  'Enviaste un meme inapropiado al grupo de chat del trabajo por error',
  'Adoptaste un pato en secreto y lo tienes en la bañera',
  'Ordenaste una pizza con piña para compartir, sabiendo que todos la odian',
  'Pintaste el coche de tu vecino de rosa',
  'Cambiaste los nombres de las carpetas del escritorio de tu compañero',
  'Usaste el teléfono de tu jefe para hacer una llamada personal de 2 horas',
  'Escondiste el control remoto de la TV y fingiste que no sabías dónde estaba',
  'Comiste la comida de tu compañero de la nevera de la oficina',
  'Le pusiste un apodo ridículo a tu mejor amigo en todos sus contactos',
  'Cambiaste el idioma del móvil de tu hermano a uno que no entiende',
  'Usaste el dinero de la alcancía familiar para comprar comida rápida',
  'Rompiste accidentalmente el vaso favorito y lo reemplazaste con uno similar',
  'Le dijiste a tus padres que aprobaste el examen cuando en realidad suspendiste',
  'Cambiaste la hora de todos los relojes de la casa para llegar tarde a propósito',
  'Dejaste el grifo abierto durante toda la noche y culpaste a tu hermano',
  'Cambiaste las llaves de la casa por unas similares y nadie podía entrar',
  'Usaste el coche de tu padre sin permiso y le dijiste que estaba roto',
  'Compraste un gato sin decirle a tu pareja que es alérgica',
  'Cambiaste la contraseña del WiFi de tu vecino por venganza',
  'Enviaste un mensaje de amor a tu ex por error a las 3 de la madrugada',
  'Te comiste el último trozo de chocolate que estaba guardado para una ocasión especial',
  'Cambiaste los zapatos de tu hermano por otros de una talla más pequeña',
  'Usaste la tarjeta de crédito de tu pareja para comprar algo sin permiso',
  'Rompiste el jarrón más caro de la casa y lo reemplazaste con uno de plástico',
  'Le dijiste a tu jefe que estabas enfermo cuando en realidad estabas en la playa',
  'Cambiaste el orden de los canales de la TV para confundir a tu familia',
  'Usaste el perfume de tu hermana y lo dejaste casi vacío',
  'Comiste la comida del perro pensando que era para humanos',
  'Cambiaste la foto de perfil de tu mejor amigo en todas sus redes sociales',
  'Le dijiste a todos que tu compañero había renunciado cuando no era cierto',
  'Usaste el ordenador de tu hermano y borraste accidentalmente sus archivos importantes',
  'Cambiaste el aceite del coche por agua sin que nadie se diera cuenta',
  'Te quedaste con el dinero del cambio de una compra que hiciste para otra persona',
  'Enviaste un correo electrónico a toda la empresa con un chiste inapropiado',
  'Cambiaste la fecha de la reunión importante en el calendario compartido',
  'Usaste la pasta de dientes de tu pareja para limpiar las zapatillas',
  'Le dijiste a tu madre que tu hermano había roto algo cuando fuiste tú',
  'Cambiaste la configuración del termostato a 30 grados en pleno verano',
  'Comiste el último yogur que estaba guardado para el desayuno de mañana',
  'Usaste el cepillo de dientes de tu compañero de piso por error',
  'Cambiaste la alarma del móvil de tu hermano para que no se levantara',
  'Le dijiste a tu novia que tenías que trabajar cuando en realidad estabas jugando videojuegos',
  'Cambiaste el nombre de tu perro en el veterinario por uno completamente diferente',
  'Usaste el dinero del fondo común para comprar algo personal',
  'Te comiste el pastel de cumpleaños antes de la fiesta y lo reemplazaste con uno falso',
  'Cambiaste las medicinas de tu abuela por placebos',
  'Le dijiste a tu jefe que tu compañero había llegado tarde cuando no era cierto',
  'Usaste el champú para lavar los platos cuando se te acabó el detergente',
  'Cambiaste la contraseña de Netflix sin decirle a tu familia',
  'Te quedaste con el regalo de cumpleaños que alguien más había comprado',
  'Le dijiste a tu pareja que habías limpiado la casa cuando en realidad no lo hiciste',
  'Cambiaste el aceite de la cocina por uno caducado sin que nadie se diera cuenta',
  'Usaste el dinero de la hucha de tu hermano pequeño para comprar dulces',
  'Enviaste un mensaje comprometedor al grupo de WhatsApp de la familia',
  'Cambiaste la hora del reloj de la cocina para llegar tarde a propósito',
  'Te comiste el último helado que estaba guardado en el congelador',
  'Le dijiste a tu madre que habías estudiado cuando en realidad no lo hiciste',
  'Cambiaste el orden de los libros en la estantería para confundir a tu hermano',
  'Usaste el móvil de tu pareja para enviar mensajes a tus amigos sin permiso',
  'Te quedaste con el cambio de una compra que no era tuya',
  'Cambiaste la configuración del router para que solo tu dispositivo funcionara',
  'Le dijiste a tu jefe que tu ordenador estaba roto cuando solo querías un día libre',
  'Usaste el perfume caro de tu hermana y lo dejaste casi vacío',
  'Cambiaste las llaves del coche por otras similares y nadie podía arrancarlo',
  'Te comiste la última galleta que estaba guardada para tu hermano',
  'Le dijiste a tu novia que habías cocinado cuando en realidad pediste comida a domicilio',
  'Cambiaste el idioma de todos los dispositivos de la casa a uno desconocido',
  'Usaste el dinero de la cena familiar para comprar algo personal',
  'Enviaste un correo con información confidencial a la persona equivocada',
  'Cambiaste la foto de la pantalla de bloqueo de tu hermano por una vergonzosa',
  'Te quedaste con el regalo de Navidad que alguien más había comprado',
  'Le dijiste a tu madre que habías recogido tu habitación cuando no era cierto',
  'Cambiaste el aceite del coche por uno de calidad inferior sin decir nada',
  'Usaste el champú de lujo para lavar el coche',
  'Te comiste el último trozo de pizza que estaba guardado para tu pareja',
  'Cambiaste la hora del despertador de tu hermano para que llegara tarde',
  'Le dijiste a tu jefe que tu compañero había cometido un error cuando fuiste tú',
  'Usaste el dinero del fondo de emergencia para comprar algo innecesario',
  'Cambiaste la configuración del aire acondicionado cuando todos tenían calor',
  'Enviaste un mensaje privado a toda la lista de contactos por error',
  'Te quedaste con el último trozo de tarta que estaba guardado para una ocasión especial',
  'Cambiaste el nombre de tu perro en el chip por completo',
  'Le dijiste a tu pareja que habías pagado las facturas cuando no lo hiciste',
  'Usaste el perfume de tu hermana y lo reemplazaste con agua',
  'Cambiaste las llaves de la oficina por otras similares',
  'Te comiste el último yogur que estaba guardado para el desayuno',
  'Le dijiste a tu madre que habías hecho la compra cuando en realidad no lo hiciste',
  'Cambiaste la contraseña del correo electrónico de tu hermano sin decirle',
  'Usaste el dinero de la hucha familiar para comprar algo personal',
  'Enviaste un mensaje de texto a tu ex cuando querías enviarlo a tu mejor amigo',
  'Cambiaste la foto de perfil de tu mejor amigo en todas sus cuentas',
  'Te quedaste con el cambio de una compra que alguien más había hecho',
  'Le dijiste a tu jefe que habías terminado el proyecto cuando no era cierto',
  'Cambiaste el aceite de la cocina por uno de otra marca sin que nadie se diera cuenta',
  'Usaste el champú caro para lavar los platos',
  'Te comiste el último trozo de chocolate que estaba guardado para tu pareja',
  'Cambiaste la hora de la alarma de tu hermano para que no se levantara',
  'Le dijiste a tu madre que habías estudiado para el examen cuando no lo hiciste',
  'Usaste el dinero del fondo común para comprar algo sin consultar',
  'Cambiaste la configuración del router para que solo tu ordenador funcionara',
  'Enviaste un correo electrónico con información confidencial al destinatario equivocado',
  'Te quedaste con el último helado que estaba guardado en el congelador',
  'Cambiaste el nombre del perro en el veterinario por completo',
  'Le dijiste a tu pareja que habías limpiado cuando en realidad no lo hiciste',
  'Usaste el perfume de lujo para limpiar los zapatos',
  'Cambiaste las llaves del coche sin que nadie se diera cuenta',
  'Te comiste la última galleta que estaba guardada para tu hermano',
  'Le dijiste a tu jefe que tu ordenador estaba roto cuando solo querías un día libre',
];

export const SITUATION_THEMES = {
  oficina: [
    'Cambiaste el azúcar por la sal en la cafetera de la oficina',
    'Usaste el teléfono de tu jefe para hacer una llamada personal de 2 horas',
    'Comiste la comida de tu compañero de la nevera de la oficina',
    'Cambiaste los nombres de las carpetas del escritorio de tu compañero',
    'Enviaste un meme inapropiado al grupo de chat del trabajo por error',
    'Enviaste un correo electrónico a toda la empresa con un chiste inapropiado',
    'Cambiaste la fecha de la reunión importante en el calendario compartido',
    'Le dijiste a tu jefe que tu compañero había llegado tarde cuando no era cierto',
    'Le dijiste a tu jefe que tu compañero había cometido un error cuando fuiste tú',
    'Le dijiste a tu jefe que tu ordenador estaba roto cuando solo querías un día libre',
    'Le dijiste a tu jefe que habías terminado el proyecto cuando no era cierto',
    'Cambiaste las llaves de la oficina por otras similares',
    'Enviaste un correo con información confidencial a la persona equivocada',
    'Enviaste un correo electrónico con información confidencial al destinatario equivocado',
    'Cambiaste la configuración del router para que solo tu dispositivo funcionara',
    'Cambiaste la configuración del router para que solo tu ordenador funcionara',
  ],
  familiar: [
    'Te comiste la última porción de tarta de cumpleaños y culpaste a tu hermano pequeño',
    'Rompiste la silla favorita de tu abuela y la escondiste en el armario',
    'Usaste el champú más caro de tu pareja para lavar al perro',
    'Le dijiste a tus padres que aprobaste el examen cuando en realidad suspendiste',
    'Usaste el dinero de la alcancía familiar para comprar comida rápida',
    'Dejaste el grifo abierto durante toda la noche y culpaste a tu hermano',
    'Cambiaste las llaves de la casa por unas similares y nadie podía entrar',
    'Usaste el coche de tu padre sin permiso y le dijiste que estaba roto',
    'Compraste un gato sin decirle a tu pareja que es alérgica',
    'Le dijiste a tu madre que tu hermano había roto algo cuando fuiste tú',
    'Cambiaste la configuración del termostato a 30 grados en pleno verano',
    'Usaste el cepillo de dientes de tu compañero de piso por error',
    'Cambiaste la alarma del móvil de tu hermano para que no se levantara',
    'Cambiaste el nombre de tu perro en el veterinario por uno completamente diferente',
    'Usaste el dinero del fondo común para comprar algo personal',
    'Te comiste el pastel de cumpleaños antes de la fiesta y lo reemplazaste con uno falso',
    'Cambiaste las medicinas de tu abuela por placebos',
    'Usaste el dinero de la hucha de tu hermano pequeño para comprar dulces',
    'Enviaste un mensaje comprometedor al grupo de WhatsApp de la familia',
    'Cambiaste la hora del reloj de la cocina para llegar tarde a propósito',
    'Le dijiste a tu madre que habías estudiado cuando en realidad no lo hiciste',
    'Cambiaste el orden de los libros en la estantería para confundir a tu hermano',
    'Usaste el móvil de tu pareja para enviar mensajes a tus amigos sin permiso',
    'Cambiaste el idioma de todos los dispositivos de la casa a uno desconocido',
    'Usaste el dinero de la cena familiar para comprar algo personal',
    'Cambiaste la foto de la pantalla de bloqueo de tu hermano por una vergonzosa',
    'Le dijiste a tu madre que habías recogido tu habitación cuando no era cierto',
    'Usaste el dinero de la hucha familiar para comprar algo personal',
    'Cambiaste la contraseña del correo electrónico de tu hermano sin decirle',
    'Le dijiste a tu madre que habías hecho la compra cuando en realidad no lo hiciste',
    'Cambiaste la hora de la alarma de tu hermano para que no se levantara',
    'Le dijiste a tu madre que habías estudiado para el examen cuando no lo hiciste',
    'Le dijiste a tu pareja que habías limpiado cuando en realidad no lo hiciste',
  ],
  vacaciones: [
    'Le dijiste a un turista una dirección completamente equivocada a propósito',
    'Te hiciste pasar por un famoso en una cafetería para conseguir una bebida gratis',
    'Ordenaste una pizza con piña para compartir, sabiendo que todos la odian',
    'Le dijiste a tu jefe que estabas enfermo cuando en realidad estabas en la playa',
  ],
  tecnologia: [
    'Cambiaste el idioma del móvil de tu hermano a uno que no entiende',
    'Cambiaste la contraseña del WiFi de tu vecino por venganza',
    'Cambiaste la contraseña de Netflix sin decirle a tu familia',
    'Cambiaste la foto de perfil de tu mejor amigo en todas sus redes sociales',
    'Usaste el ordenador de tu hermano y borraste accidentalmente sus archivos importantes',
    'Cambiaste la configuración del router para que solo tu dispositivo funcionara',
    'Cambiaste la foto de la pantalla de bloqueo de tu hermano por una vergonzosa',
    'Cambiaste el nombre de tu perro en el chip por completo',
    'Cambiaste la configuración del router para que solo tu ordenador funcionara',
  ],
  comida: [
    'Te comiste el último trozo de chocolate que estaba guardado para una ocasión especial',
    'Comiste la comida del perro pensando que era para humanos',
    'Comiste el último yogur que estaba guardado para el desayuno de mañana',
    'Te comiste el último helado que estaba guardado en el congelador',
    'Te comiste la última galleta que estaba guardada para tu hermano',
    'Te comiste el último trozo de pizza que estaba guardado para tu pareja',
    'Te comiste el último trozo de chocolate que estaba guardado para tu pareja',
    'Te comiste el último yogur que estaba guardado para el desayuno',
  ],
  relaciones: [
    'Enviaste un mensaje de amor a tu ex por error a las 3 de la madrugada',
    'Le dijiste a tu novia que tenías que trabajar cuando en realidad estabas jugando videojuegos',
    'Le dijiste a tu pareja que habías limpiado la casa cuando en realidad no lo hiciste',
    'Le dijiste a tu novia que habías cocinado cuando en realidad pediste comida a domicilio',
    'Le dijiste a tu pareja que habías pagado las facturas cuando no lo hiciste',
    'Enviaste un mensaje de texto a tu ex cuando querías enviarlo a tu mejor amigo',
    'Le dijiste a tu pareja que habías limpiado cuando en realidad no lo hiciste',
  ],
};

export const getRandomSituation = (theme = null) => {
  let situationList = SITUATIONS;
  
  if (theme && SITUATION_THEMES[theme]) {
    situationList = SITUATION_THEMES[theme];
  }
  
  const randomIndex = Math.floor(Math.random() * situationList.length);
  return situationList[randomIndex];
};

