export const DICCIONARIO_FALSO_PALABRAS = [
  { palabra: "Abulia", definicion: "Falta de voluntad o de energía para moverse o tomar decisiones." },
  { palabra: "Almibarado", definicion: "Excesivamente dulce, suave o delicado en el trato o en el habla." },
  { palabra: "Limerencia", definicion: "Estado mental involuntario, propio de la atracción romántica, que se caracteriza por pensamientos y fantasías obsesivas." },
  { palabra: "Zaranjajo", definicion: "Persona despreciable, irresoluta y de poco valor." },
  { palabra: "Petricor", definicion: "El nombre que recibe el olor que se produce al caer la lluvia en los suelos secos." },
  { palabra: "Jitanjáfora", definicion: "Texto carente de sentido cuyo valor estético se basa en la sonoridad y en el poder evocador de las palabras." },
  { palabra: "Uebos", definicion: "(Del latín 'opus est') Necesidad, cosa necesaria." },
  { palabra: "Serendipia", definicion: "Hallazgo valioso e inesperado que se produce de manera accidental o casual." },
  { palabra: "Abuhado", definicion: "Hinchado o abotagado, especialmente el rostro." },
  { palabra: "Glabela", definicion: "Parte del cráneo, lisa y sin pelo, situada entre los arcos superciliares." },
  { palabra: "Esdrújula", definicion: "Palabra que tiene el acento en la antepenúltima sílaba." },
  { palabra: "Prolijo", definicion: "Dilatado, largo, lento en ejecutarse." },
  { palabra: "Intrínseco", definicion: "Que es esencial y permanente en un ser o cosa, por oposición a lo extrínseco." },
  { palabra: "Extemporáneo", definicion: "Que se hace o sucede fuera de tiempo." },
  { palabra: "Sesquipedal", definicion: "Dicho de una palabra: Muy larga, con muchas sílabas." },
  { palabra: "Epítome", definicion: "Resumen o compendio de una obra extensa." },
  { palabra: "Taciturno", definicion: "Que habitualmente es callado o poco comunicativo." },
  { palabra: "Sublime", definicion: "Excelso, eminente, de elevación extraordinaria." },
  { palabra: "Efímero", definicion: "De corta duración." },
  { palabra: "Inane", definicion: "Falto de contenido, vacío, sin sentido." },
  { palabra: "Axioma", definicion: "Proposición tan clara y evidente que se admite sin necesidad de demostración." },
  { palabra: "Bucólico", definicion: "Perteneciente o relativo a la vida pastoril o campestre." },
  { palabra: "Cacofonía", definicion: "Sonido desagradable producido por la combinación de palabras o sílabas." },
  { palabra: "Déspota", definicion: "Persona que abusa de su autoridad y trata con rigor a sus subordinados." },
  { palabra: "Efímero", definicion: "De corta duración." },
  { palabra: "Fugaz", definicion: "Que pasa rápidamente, que dura poco tiempo." },
  { palabra: "Gélido", definicion: "Muy frío, helado." },
  { palabra: "Hedonista", definicion: "Persona que considera el placer como el fin supremo de la vida." },
  { palabra: "Idílico", definicion: "Que tiene las características de un idilio, especialmente por ser agradable y placentero." },
  { palabra: "Jocoso", definicion: "Que tiene gracia o produce risa." },
  { palabra: "Kafkiano", definicion: "Relativo a situaciones absurdas y complejas, propias de las obras de Kafka." },
  { palabra: "Lúgubre", definicion: "Triste, sombrío, que causa melancolía." },
  { palabra: "Mellifluo", definicion: "Que es suave y dulce, especialmente referido a la voz o al habla." },
  { palabra: "Nefasto", definicion: "Que trae o causa desgracias o males." },
  { palabra: "Oneroso", definicion: "Que causa dificultades o molestias, gravoso." },
  { palabra: "Paradójico", definicion: "Que encierra o implica una paradoja, que contradice la lógica común." },
  { palabra: "Quimérico", definicion: "Que es producto de la imaginación o es imposible de realizar." },
  { palabra: "Reticente", definicion: "Que se muestra poco dispuesto a hablar o a hacer algo." },
  { palabra: "Sibilo", definicion: "Sonido agudo y silbante que se produce al pasar el aire por un conducto estrecho." },
  { palabra: "Tenebroso", definicion: "Oscuro, sombrío, que causa miedo o terror." },
  { palabra: "Utópico", definicion: "Que pertenece a la utopía o es irrealizable." },
  { palabra: "Vexatorio", definicion: "Que causa molestia, vejación o fastidio." },
  { palabra: "Xenófobo", definicion: "Que tiene aversión, odio o miedo a los extranjeros." },
  { palabra: "Yermo", definicion: "Desierto, sin cultivar, estéril." },
  { palabra: "Zalamero", definicion: "Que muestra excesiva adulación o halago." },
  { palabra: "Abarrotar", definicion: "Llenar algo completamente, especialmente un lugar o espacio." },
  { palabra: "Benevolente", definicion: "Que muestra buena voluntad o deseo de hacer el bien." },
  { palabra: "Cacarear", definicion: "Emitir el sonido característico de las gallinas." },
  { palabra: "Dilapidar", definicion: "Gastar o consumir algo de manera imprudente y excesiva." },
  { palabra: "Efluvio", definicion: "Emanación o exhalación, especialmente de un olor." },
  { palabra: "Fugaz", definicion: "Que pasa rápidamente, de corta duración." },
  { palabra: "Garrulo", definicion: "Que habla mucho y sin orden ni concierto." },
  { palabra: "Hediondo", definicion: "Que despide un olor muy desagradable." },
  { palabra: "Idioma", definicion: "Sistema de comunicación verbal o escrito propio de una comunidad." },
  { palabra: "Jocundidad", definicion: "Alegría, regocijo, estado de ánimo festivo." },
  { palabra: "Lacónico", definicion: "Que se expresa con pocas palabras, conciso." },
  { palabra: "Mendaz", definicion: "Que miente o tiene tendencia a mentir." },
  { palabra: "Nefelibata", definicion: "Persona distraída, que no tiene los pies en la tierra." },
  { palabra: "Oneroso", definicion: "Que causa dificultades o molestias, gravoso." },
  { palabra: "Pérfido", definicion: "Que traiciona la confianza o la lealtad esperada." },
  { palabra: "Quid", definicion: "El punto esencial o la cuestión principal de un asunto." },
  { palabra: "Refulgente", definicion: "Que brilla intensamente, resplandeciente." },
  { palabra: "Sibilino", definicion: "Que es ambiguo, enigmático o difícil de interpretar." },
  { palabra: "Tergiversar", definicion: "Dar a las palabras o acciones un sentido distinto del que tienen." },
  { palabra: "Ubicuo", definicion: "Que está presente en todas partes al mismo tiempo." },
  { palabra: "Vexatorio", definicion: "Que causa molestia, vejación o fastidio." },
  { palabra: "Xilófago", definicion: "Que se alimenta de madera." },
  { palabra: "Yacente", definicion: "Que está tumbado o recostado." },
  { palabra: "Zafio", definicion: "De mal gusto, grosero, sin educación." },
  { palabra: "Acuoso", definicion: "Que tiene mucha agua o está relacionado con ella." },
  { palabra: "Blandengue", definicion: "Que es débil, sin carácter o demasiado suave." },
  { palabra: "Cacofonía", definicion: "Sonido desagradable producido por la combinación de palabras." },
  { palabra: "Diluvio", definicion: "Lluvia muy intensa y prolongada." },
  { palabra: "Efímero", definicion: "De corta duración, pasajero." },
  { palabra: "Fulgurante", definicion: "Que brilla intensamente como un relámpago." },
  { palabra: "Gárrulo", definicion: "Que habla mucho y sin orden." },
  { palabra: "Hedonismo", definicion: "Doctrina filosófica que considera el placer como el bien supremo." },
  { palabra: "Idiosincrasia", definicion: "Característica peculiar de una persona o grupo." },
  { palabra: "Jocoso", definicion: "Que tiene gracia o produce risa." },
  { palabra: "Lánguido", definicion: "Que muestra debilidad, falta de energía o vigor." },
  { palabra: "Mellifluo", definicion: "Que es suave y dulce, especialmente la voz." },
  { palabra: "Nefelibata", definicion: "Persona distraída, que vive en las nubes." },
  { palabra: "Oneroso", definicion: "Que causa dificultades o molestias." },
  { palabra: "Pérfido", definicion: "Que traiciona la confianza." },
  { palabra: "Quimérico", definicion: "Que es producto de la imaginación." },
  { palabra: "Refulgente", definicion: "Que brilla intensamente." },
  { palabra: "Sibilino", definicion: "Que es ambiguo o enigmático." },
  { palabra: "Tergiversar", definicion: "Dar sentido distinto a las palabras." },
  { palabra: "Ubicuo", definicion: "Que está presente en todas partes." },
  { palabra: "Vexatorio", definicion: "Que causa molestia o fastidio." },
  { palabra: "Xenófobo", definicion: "Que tiene aversión a los extranjeros." },
  { palabra: "Yermo", definicion: "Desierto, sin cultivar." },
  { palabra: "Zalamero", definicion: "Que muestra excesiva adulación." },
  { palabra: "Abstruso", definicion: "Difícil de entender o comprender." },
  { palabra: "Benevolente", definicion: "Que muestra buena voluntad." },
  { palabra: "Cacofonía", definicion: "Sonido desagradable." },
  { palabra: "Dilapidar", definicion: "Gastar de manera imprudente." },
  { palabra: "Efluvio", definicion: "Emanación o exhalación de un olor." },
  { palabra: "Fugaz", definicion: "Que pasa rápidamente." },
  { palabra: "Garrulo", definicion: "Que habla mucho sin orden." },
  { palabra: "Hediondo", definicion: "Que despide olor desagradable." },
  { palabra: "Idioma", definicion: "Sistema de comunicación verbal." },
  { palabra: "Jocundidad", definicion: "Alegría, regocijo." },
  { palabra: "Lacónico", definicion: "Que se expresa con pocas palabras." },
  { palabra: "Mendaz", definicion: "Que miente o tiene tendencia a mentir." },
  { palabra: "Nefasto", definicion: "Que trae desgracias." },
  { palabra: "Oneroso", definicion: "Que causa dificultades." },
  { palabra: "Pérfido", definicion: "Que traiciona la confianza." },
  { palabra: "Quid", definicion: "El punto esencial de un asunto." },
  { palabra: "Refulgente", definicion: "Que brilla intensamente." },
  { palabra: "Sibilino", definicion: "Que es ambiguo o enigmático." },
  { palabra: "Tergiversar", definicion: "Dar sentido distinto." },
  { palabra: "Ubicuo", definicion: "Presente en todas partes." },
  { palabra: "Vexatorio", definicion: "Que causa molestia." },
  { palabra: "Xilófago", definicion: "Que se alimenta de madera." },
  { palabra: "Yacente", definicion: "Que está tumbado." },
  { palabra: "Zafio", definicion: "De mal gusto, grosero." },
  { palabra: "Axioma", definicion: "Proposición evidente que se admite sin demostración." },
  { palabra: "Bucólico", definicion: "Perteneciente a la vida campestre." },
  { palabra: "Cacofonía", definicion: "Sonido desagradable por combinación de palabras." },
  { palabra: "Déspota", definicion: "Persona que abusa de su autoridad." },
  { palabra: "Efímero", definicion: "De corta duración." },
  { palabra: "Fugaz", definicion: "Que pasa rápidamente." },
  { palabra: "Gélido", definicion: "Muy frío, helado." },
  { palabra: "Hedonista", definicion: "Persona que considera el placer como fin supremo." },
  { palabra: "Idílico", definicion: "Agradable y placentero." },
  { palabra: "Jocoso", definicion: "Que tiene gracia o produce risa." },
  { palabra: "Kafkiano", definicion: "Relativo a situaciones absurdas y complejas." },
  { palabra: "Lúgubre", definicion: "Triste, sombrío." },
  { palabra: "Mellifluo", definicion: "Suave y dulce, especialmente la voz." },
  { palabra: "Nefasto", definicion: "Que trae desgracias." },
  { palabra: "Oneroso", definicion: "Que causa dificultades." },
  { palabra: "Paradójico", definicion: "Que encierra una paradoja." },
  { palabra: "Quimérico", definicion: "Producto de la imaginación." },
  { palabra: "Reticente", definicion: "Poco dispuesto a hablar." },
  { palabra: "Sibilo", definicion: "Sonido agudo y silbante." },
  { palabra: "Tenebroso", definicion: "Oscuro, sombrío." },
  { palabra: "Utópico", definicion: "Irrealizable." },
  { palabra: "Vexatorio", definicion: "Que causa molestia." },
  { palabra: "Xenófobo", definicion: "Que tiene aversión a extranjeros." },
  { palabra: "Yermo", definicion: "Desierto, sin cultivar." },
  { palabra: "Zalamero", definicion: "Que muestra excesiva adulación." },
];

// Función para obtener una palabra aleatoria
export const getRandomWord = () => {
  const randomIndex = Math.floor(Math.random() * DICCIONARIO_FALSO_PALABRAS.length);
  return DICCIONARIO_FALSO_PALABRAS[randomIndex];
};

// Función para obtener estadísticas de palabras
export const getWordsStats = () => {
  return {
    total: DICCIONARIO_FALSO_PALABRAS.length,
    averageLength: Math.round(
      DICCIONARIO_FALSO_PALABRAS.reduce((sum, word) => sum + word.palabra.length, 0) / 
      DICCIONARIO_FALSO_PALABRAS.length
    ),
    longestWord: DICCIONARIO_FALSO_PALABRAS.reduce((longest, word) => 
      word.palabra.length > longest.palabra.length ? word : longest
    ),
    shortestWord: DICCIONARIO_FALSO_PALABRAS.reduce((shortest, word) => 
      word.palabra.length < shortest.palabra.length ? word : shortest
    ),
  };
};
