// Definiciones de roles para Blood on the Clocktower

export const ROLES = {
  // ALDEANOS (Townsfolk) - Equipo del Bien
  LAVANDERA: {
    id: 'lavandera',
    name: 'Lavandera',
    nameEn: 'Washerwoman',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Empiezas sabiendo que uno de dos jugadores es un Aldeano específico.',
    firstNight: true,
    otherNights: false,
  },
  BIBLIOTECARIO: {
    id: 'bibliotecario',
    name: 'Bibliotecario',
    nameEn: 'Librarian',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Empiezas sabiendo que uno de dos jugadores es un Forastero.',
    firstNight: true,
    otherNights: false,
  },
  INVESTIGADOR: {
    id: 'investigador',
    name: 'Investigador',
    nameEn: 'Investigator',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Empiezas sabiendo que uno de dos jugadores es un Esbirro.',
    firstNight: true,
    otherNights: false,
  },
  COCINERO: {
    id: 'cocinero',
    name: 'Cocinero',
    nameEn: 'Chef',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Empiezas sabiendo cuántos pares de jugadores malvados están sentados uno al lado del otro.',
    firstNight: true,
    otherNights: false,
  },
  EMPATICO: {
    id: 'empatico',
    name: 'Empático',
    nameEn: 'Empath',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Cada noche, sientes cuántos de tus 2 vecinos vivos son malvados.',
    firstNight: false,
    otherNights: true,
  },
  ADIVINO: {
    id: 'adivino',
    name: 'Adivino',
    nameEn: 'Fortune Teller',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Cada noche, elige a un jugador vivo: aprende si es el Demonio. Si hay un Adivino en el juego, hay un 50% de probabilidad de que obtengas un resultado incorrecto.',
    firstNight: false,
    otherNights: true,
  },
  MONJE: {
    id: 'monje',
    name: 'Monje',
    nameEn: 'Monk',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Cada noche, elige a un jugador (no a ti mismo): están protegido del Demonio.',
    firstNight: false,
    otherNights: true,
  },
  ALCAIDE: {
    id: 'alcaide',
    name: 'Alcaide',
    nameEn: 'Slayer',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Una vez por juego, durante el día, puedes elegir públicamente a un jugador: si es el Demonio, mueren.',
    firstNight: false,
    otherNights: false,
  },
  SOLDADO: {
    id: 'soldado',
    name: 'Soldado',
    nameEn: 'Soldier',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Eres inmune al Demonio.',
    firstNight: false,
    otherNights: false,
  },
  VIRGEN: {
    id: 'virgen',
    name: 'Virgen',
    nameEn: 'Virgin',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'La primera vez que un jugador te elige durante la discusión, si son buenos, es ejecutado inmediatamente.',
    firstNight: false,
    otherNights: false,
  },
  ENTERRADOR: {
    id: 'enterrador',
    name: 'Enterrador',
    nameEn: 'Undertaker',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Cada noche*, aprende el carácter del jugador ejecutado hoy.',
    firstNight: false,
    otherNights: true,
  },
  MAYOR: {
    id: 'mayor',
    name: 'Alcalde',
    nameEn: 'Mayor',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Si solo quedan 3 jugadores vivos y no te ejecutan, tu equipo gana.',
    firstNight: false,
    otherNights: false,
  },
  CHAMAN: {
    id: 'chaman',
    name: 'Chamán',
    nameEn: 'Ravenkeeper',
    alignment: 'good',
    team: 'townsfolk',
    ability: 'Si mueres durante la noche, elige un jugador: aprendes su carácter.',
    firstNight: false,
    otherNights: false,
  },
  CANTINERO: {
    id: 'cantinero',
    name: 'Cantinero',
    nameEn: 'Butler',
    alignment: 'good',
    team: 'outsider',
    ability: 'Cada noche, elige a un jugador vivo: no puedes votar a menos que ellos voten primero.',
    firstNight: false,
    otherNights: true,
  },

  // FORASTEROS (Outsiders) - Equipo del Bien pero con desventajas
  BORRACHO: {
    id: 'borracho',
    name: 'Borracho',
    nameEn: 'Drunk',
    alignment: 'good',
    team: 'outsider',
    ability: 'Piensas que eres un Aldeano, pero no eres bueno.',
    firstNight: false,
    otherNights: false,
  },
  RENEGADO: {
    id: 'renegado',
    name: 'Renegado',
    nameEn: 'Recluse',
    alignment: 'good',
    team: 'outsider',
    ability: 'Puedes aparecer como bueno o malvado y como Demonio o Esbirro, incluso si estás muerto.',
    firstNight: false,
    otherNights: false,
  },
  SANTO: {
    id: 'santo',
    name: 'Santo',
    nameEn: 'Saint',
    alignment: 'good',
    team: 'outsider',
    ability: 'Si eres ejecutado, todos los buenos pierden.',
    firstNight: false,
    otherNights: false,
  },
  BUFON: {
    id: 'bufon',
    name: 'Bufón',
    nameEn: 'Fool',
    alignment: 'good',
    team: 'outsider',
    ability: 'Puedes elegir no morir la primera vez que eres ejecutado.',
    firstNight: false,
    otherNights: false,
  },

  // ESBIRROS (Minions) - Equipo del Mal
  ENVENENADOR: {
    id: 'envenenador',
    name: 'Envenenador',
    nameEn: 'Poisoner',
    alignment: 'evil',
    team: 'minion',
    ability: 'Cada noche, elige a un jugador: están envenenados esta noche y mañana.',
    firstNight: false,
    otherNights: true,
  },
  ESPIA: {
    id: 'espia',
    name: 'Espía',
    nameEn: 'Spy',
    alignment: 'evil',
    team: 'minion',
    ability: 'Puedes aparecer como bueno para el Investigador y como el Demonio para el Adivino. Puedes ver el Grimorio.',
    firstNight: false,
    otherNights: false,
  },
  BARONES: {
    id: 'barones',
    name: 'Barones',
    nameEn: 'Baron',
    alignment: 'evil',
    team: 'minion',
    ability: 'Hay extra Forasteros en la ciudad. 1 o 2 jugadores buenos son Forasteros.',
    firstNight: false,
    otherNights: false,
  },
  ESCARLATA: {
    id: 'escarleta',
    name: 'Escarlata',
    nameEn: 'Scarlet Woman',
    alignment: 'evil',
    team: 'minion',
    ability: 'Si hay 4 o menos jugadores vivos y el Demonio muere, te conviertes en el Demonio.',
    firstNight: false,
    otherNights: false,
  },

  // DEMONIOS (Demons)
  IMP: {
    id: 'imp',
    name: 'Diablillo',
    nameEn: 'Imp',
    alignment: 'evil',
    team: 'demon',
    ability: 'Cada noche*, elige a un jugador: mueren. Si mueres por la ejecución, elige un Esbirro vivo: se convierte en el Demonio.',
    firstNight: false,
    otherNights: true,
  },
};

// Configuración de guiones
export const SCRIPT_TROUBLE_BREWING = {
  id: 'trouble-brewing',
  name: 'Trouble Brewing',
  nameEn: 'Trouble Brewing',
  townsfolk: [
    'lavandera',
    'bibliotecario',
    'investigador',
    'cocinero',
    'empatico',
    'adivino',
    'monje',
    'alcaide',
    'soldado',
    'virgen',
    'enterrador',
    'mayor',
    'chaman',
  ],
  outsiders: ['borracho', 'renegado', 'santo', 'bufon', 'cantinero'],
  minions: ['envenenador', 'espia', 'barones', 'escarleta'],
  demon: ['imp'],
};

// Configuración de jugadores por número de participantes
export const PLAYER_CONFIG = {
  5: { townsfolk: 3, outsiders: 0, minions: 1, demon: 1 },
  6: { townsfolk: 3, outsiders: 1, minions: 1, demon: 1 },
  7: { townsfolk: 5, outsiders: 0, minions: 1, demon: 1 },
  8: { townsfolk: 5, outsiders: 1, minions: 1, demon: 1 },
  9: { townsfolk: 5, outsiders: 2, minions: 1, demon: 1 },
  10: { townsfolk: 7, outsiders: 0, minions: 2, demon: 1 },
  11: { townsfolk: 7, outsiders: 1, minions: 2, demon: 1 },
  12: { townsfolk: 7, outsiders: 2, minions: 2, demon: 1 },
  13: { townsfolk: 9, outsiders: 0, minions: 3, demon: 1 },
  14: { townsfolk: 9, outsiders: 1, minions: 3, demon: 1 },
  15: { townsfolk: 9, outsiders: 2, minions: 3, demon: 1 },
};

export const GAME_CONFIG = {
  MIN_PLAYERS: 5,
  MAX_PLAYERS: 15,
  DISCUSSION_TIME: 300000, // 5 minutos en milisegundos
  NOMINATION_TIME: 60000, // 1 minuto en milisegundos
  VOTING_TIME: 30000, // 30 segundos en milisegundos
  NIGHT_TIME: 120000, // 2 minutos en milisegundos
};

