export const CATEGORIES = {
  personajesPeliculas: {
    id: 'personajesPeliculas',
    name: 'Personajes de Películas',
    words: [
      'Harry Potter',
      'Darth Vader',
      'Katniss Everdeen',
      'Elsa',
      'Iron Man',
      'Jack Sparrow',
      'Sherlock Holmes',
      'Hermione Granger',
      'Luke Skywalker',
      'Wonder Woman',
      'Batman',
      'Gandalf',
      'Titanic',
      'Forrest Gump',
      'E.T.',
    ],
  },
  animales: {
    id: 'animales',
    name: 'Animales',
    words: [
      'León',
      'Pingüino',
      'Jirafa',
      'Delfín',
      'Ornitorrinco',
      'Tiranosaurio Rex',
      'Elefante',
      'Tigre',
      'Panda',
      'Águila',
      'Ballena',
      'Cocodrilo',
    ],
  },
  celebridades: {
    id: 'celebridades',
    name: 'Celebridades',
    words: [
      'Shakira',
      'Lionel Messi',
      'Frida Kahlo',
      'Elon Musk',
      'Taylor Swift',
      'Will Smith',
      'Leonardo DiCaprio',
      'Beyoncé',
      'Cristiano Ronaldo',
      'Oprah Winfrey',
    ],
  },
  superheroes: {
    id: 'superheroes',
    name: 'Superhéroes',
    words: [
      'Superman',
      'Spider-Man',
      'Wonder Woman',
      'Hulk',
      'Capitán América',
      'Thor',
      'Black Widow',
      'Iron Man',
      'Batman',
      'Flash',
    ],
  },
  objetosCasa: {
    id: 'objetosCasa',
    name: 'Objetos de Casa',
    words: [
      'Microondas',
      'Sofá',
      'Lavadora',
      'Tostadora',
      'Mando a distancia',
      'Cepillo de dientes',
      'Almohada',
      'Espejo',
      'Televisor',
      'Refrigerador',
    ],
  },
  personajesHistoricos: {
    id: 'personajesHistoricos',
    name: 'Personajes Históricos',
    words: [
      'Napoleón Bonaparte',
      'Cleopatra',
      'Leonardo da Vinci',
      'Einstein',
      'Gandhi',
      'Julio César',
      'María Antonieta',
      'Galileo',
      'Marco Polo',
      'Mozart',
    ],
  },
  objetosTecnologia: {
    id: 'objetosTecnologia',
    name: 'Tecnología',
    words: [
      'Smartphone',
      'Laptop',
      'Tablet',
      'Auriculares',
      'Drone',
      'Smartwatch',
      'Cámara',
      'Ratón',
      'Teclado',
      'Router',
    ],
  },
};

export const DEFAULT_TIME_LIMIT = 60; // segundos
export const TILT_THRESHOLD = 0.7; // umbral para detectar inclinación
