// Datos de citas famosas para el juego Maestro de las Citas
// Cada cita tiene: id, quote (texto), options (array de 4 opciones), correctAnswer (índice de la opción correcta), category

export const CITAS_DATA = [
  // CINE
  {
    id: 1,
    quote: 'Voy a hacerle una oferta que no podrá rechazar.',
    options: ['El Padrino', 'Scarface', 'Pulp Fiction', 'Casablanca'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 2,
    quote: '¡Hasta el infinito y más allá!',
    options: ['Toy Story', 'Shrek', 'Buscando a Nemo', 'Cars'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 3,
    quote: 'La vida es como una caja de bombones, nunca sabes lo que te va a tocar.',
    options: ['Forrest Gump', 'Titanic', 'El Club de la Lucha', 'Cadena Perpetua'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 4,
    quote: 'Houston, tenemos un problema.',
    options: ['Apollo 13', 'Armageddon', 'Gravity', 'Interstellar'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 5,
    quote: 'Que la fuerza te acompañe.',
    options: ['Star Wars', 'Star Trek', 'Dune', 'Blade Runner'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 6,
    quote: 'May the Force be with you.',
    options: ['Star Wars', 'Star Trek', 'The Matrix', 'Blade Runner'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 7,
    quote: 'Aquí está Johnny!',
    options: ['El Resplandor', 'Psicosis', 'El Exorcista', 'Halloween'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 8,
    quote: 'Aquí estoy yo.',
    options: ['Terminator 2', 'Robocop', 'Matrix', 'Blade Runner'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 9,
    quote: 'Yo soy tu padre.',
    options: ['El Imperio Contraataca', 'El Retorno del Jedi', 'Una Nueva Esperanza', 'La Amenaza Fantasma'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 10,
    quote: 'Frankly, my dear, I don\'t give a damn.',
    options: ['Lo que el viento se llevó', 'Casablanca', 'Ciudadano Kane', 'El Gran Dictador'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 11,
    quote: 'Toto, tengo la sensación de que ya no estamos en Kansas.',
    options: ['El Mago de Oz', 'Blancanieves', 'Cenicienta', 'La Bella y la Bestia'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 12,
    quote: 'Aquí está mirando, chico.',
    options: ['Casablanca', 'El Padrino', 'El Gran Dictador', 'Lo que el viento se llevó'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 13,
    quote: 'Buenas noches, buenas noches. Es una noche tan hermosa.',
    options: ['Drácula', 'Frankenstein', 'El Fantasma de la Ópera', 'Nosferatu'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 14,
    quote: 'Mi tesoro.',
    options: ['El Señor de los Anillos', 'Harry Potter', 'Las Crónicas de Narnia', 'El Hobbit'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 15,
    quote: 'Nunca me digas las probabilidades.',
    options: ['El Imperio Contraataca', 'Una Nueva Esperanza', 'El Retorno del Jedi', 'El Despertar de la Fuerza'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 16,
    quote: '¡Yo soy Iron Man!',
    options: ['Iron Man', 'Los Vengadores', 'Iron Man 2', 'Capitán América'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 17,
    quote: 'Con gran poder viene una gran responsabilidad.',
    options: ['Spider-Man', 'Batman', 'Superman', 'X-Men'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 18,
    quote: 'Shaken, not stirred.',
    options: ['James Bond', 'Mission Impossible', 'Bourne', 'Kingsman'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 19,
    quote: 'Yo comeré tus hígados con algunas judías y un buen Chianti.',
    options: ['El Silencio de los Corderos', 'Psicosis', 'El Resplandor', 'El Exorcista'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 20,
    quote: '¡Volveré!',
    options: ['Terminator', 'Rambo', 'Depredador', 'Robocop'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 21,
    quote: '¡Mamá siempre dijo que la vida es como una caja de bombones!',
    options: ['Forrest Gump', 'El Show de Truman', 'Big', 'Tootsie'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 22,
    quote: 'Oficial, puedo explicarlo...',
    options: ['Rápido y Furioso', 'Bad Boys', 'Lethal Weapon', 'Die Hard'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 23,
    quote: 'El problema no es el problema. El problema es tu actitud sobre el problema.',
    options: ['Piratas del Caribe', 'Matrix', 'Gladiator', 'Troy'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 24,
    quote: 'Nunca me rendiré, nunca me rendiré.',
    options: ['Braveheart', 'Gladiator', '300', 'Troy'],
    correctAnswer: 0,
    category: 'Cine',
  },
  {
    id: 25,
    quote: 'Ve y hazlo.',
    options: ['Forrest Gump', 'Shawshank Redemption', 'El Club de la Lucha', 'El Padrino'],
    correctAnswer: 0,
    category: 'Cine',
  },
  
  // LITERATURA
  {
    id: 26,
    quote: 'Elemental, mi querido Watson.',
    options: ['Sherlock Holmes (Libros)', 'Agatha Christie', 'Edgar Allan Poe', 'Julio Verne'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 27,
    quote: 'Ser o no ser, esa es la cuestión.',
    options: ['Hamlet de Shakespeare', 'Romeo y Julieta', 'Macbeth', 'El Rey Lear'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 28,
    quote: 'En un lugar de la Mancha, de cuyo nombre no quiero acordarme...',
    options: ['Don Quijote de la Mancha', 'Lazarillo de Tormes', 'La Celestina', 'El Cid'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 29,
    quote: 'Carpe diem.',
    options: ['Horacio', 'Virgilio', 'Ovidio', 'Cicerón'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 30,
    quote: '¡Qué grande es el mundo!',
    options: ['La Odisea', 'La Ilíada', 'La Eneida', 'Las Metamorfosis'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 31,
    quote: 'Era el mejor de los tiempos, era el peor de los tiempos.',
    options: ['Historia de dos ciudades', 'Oliver Twist', 'David Copperfield', 'Grandes Esperanzas'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 32,
    quote: 'Llamadme Ismael.',
    options: ['Moby Dick', 'El Viejo y el Mar', 'La Isla del Tesoro', 'Robinson Crusoe'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 33,
    quote: 'En un agujero en el suelo vivía un hobbit.',
    options: ['El Hobbit', 'El Señor de los Anillos', 'El Silmarillion', 'Cuentos Inconclusos'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 34,
    quote: 'Todas las familias felices se parecen; cada familia infeliz es infeliz a su manera.',
    options: ['Ana Karenina', 'Guerra y Paz', 'Crimen y Castigo', 'Los Hermanos Karamázov'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 35,
    quote: 'En la ciudad de Barcelona, en la calle de los Arcos, número 8, vivía un hombre llamado...',
    options: ['La Sombra del Viento', 'Marina', 'El Prisionero del Cielo', 'El Laberinto de los Espíritus'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 36,
    quote: 'Fue en el mejor de los mundos posibles.',
    options: ['Cándido', 'Cartas Persas', 'El Contrato Social', 'Las Confesiones'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 37,
    quote: '¡Que viva la Pepa!',
    options: ['La Pepa (Constitución de 1812)', 'La Regenta', 'Fortunata y Jacinta', 'Pepita Jiménez'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 38,
    quote: 'Todo lo que sé lo aprendí de los libros.',
    options: ['Jane Austen', 'Charlotte Brontë', 'Emily Brontë', 'Virginia Woolf'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 39,
    quote: 'Y cuando despertó, el dinosaurio todavía estaba ahí.',
    options: ['Augusto Monterroso', 'Jorge Luis Borges', 'Julio Cortázar', 'Gabriel García Márquez'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 40,
    quote: 'Muchos años después, frente al pelotón de fusilamiento...',
    options: ['Cien años de soledad', 'El amor en los tiempos del cólera', 'Crónica de una muerte anunciada', 'El otoño del patriarca'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 41,
    quote: 'El mundo es un libro y aquellos que no viajan leen solo una página.',
    options: ['San Agustín', 'Cicerón', 'Séneca', 'Marco Aurelio'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 42,
    quote: 'No hay nada más difícil de soportar que una serie de buenos días.',
    options: ['El Principito', 'El Extranjero', 'La Peste', 'El Mito de Sísifo'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 43,
    quote: 'La imaginación es más importante que el conocimiento.',
    options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Stephen Hawking'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 44,
    quote: 'El tiempo es la imagen móvil de la eternidad.',
    options: ['Platón', 'Aristóteles', 'Sócrates', 'Heráclito'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 45,
    quote: 'No hay nada nuevo bajo el sol.',
    options: ['Eclesiastés', 'Génesis', 'Salmos', 'Proverbios'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 46,
    quote: 'En la aldea todo el mundo sabía que el coronel no tenía nadie a quien escribirle.',
    options: ['El Coronel no tiene quien le escriba', 'Cien años de soledad', 'Crónica de una muerte anunciada', 'El otoño del patriarca'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 47,
    quote: 'La vida es un sueño.',
    options: ['Pedro Calderón de la Barca', 'Lope de Vega', 'Miguel de Cervantes', 'Francisco de Quevedo'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 48,
    quote: 'El hombre es un animal racional.',
    options: ['Aristóteles', 'Platón', 'Sócrates', 'Heráclito'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 49,
    quote: 'La literatura es la mentira en la cual se cree de verdad.',
    options: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Julio Cortázar', 'Mario Vargas Llosa'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  {
    id: 50,
    quote: 'Un libro debe ser el hacha que rompa el mar helado dentro de nosotros.',
    options: ['Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Stefan Zweig'],
    correctAnswer: 0,
    category: 'Literatura',
  },
  
  // FILOSOFÍA
  {
    id: 51,
    quote: 'El hombre es un lobo para el hombre.',
    options: ['Plauto', 'Aristóteles', 'Platón', 'Séneca'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 52,
    quote: 'Conócete a ti mismo.',
    options: ['Sócrates', 'Platón', 'Aristóteles', 'Tales de Mileto'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 53,
    quote: 'Yo solo sé que no sé nada.',
    options: ['Sócrates', 'Platón', 'Aristóteles', 'Epicuro'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 54,
    quote: 'La única cosa que sé es que no sé nada.',
    options: ['Sócrates', 'Platón', 'Aristóteles', 'Heráclito'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 55,
    quote: 'El hombre es la medida de todas las cosas.',
    options: ['Protágoras', 'Sócrates', 'Platón', 'Aristóteles'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 56,
    quote: 'Pienso, luego existo.',
    options: ['René Descartes', 'Immanuel Kant', 'Baruch Spinoza', 'Gottfried Leibniz'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 57,
    quote: 'El hombre nace libre, pero en todas partes está encadenado.',
    options: ['Jean-Jacques Rousseau', 'Voltaire', 'Montesquieu', 'Diderot'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 58,
    quote: 'La vida sin examinar no merece ser vivida.',
    options: ['Sócrates', 'Platón', 'Aristóteles', 'Epicuro'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 59,
    quote: 'Dios ha muerto.',
    options: ['Friedrich Nietzsche', 'Arthur Schopenhauer', 'Søren Kierkegaard', 'Martin Heidegger'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 60,
    quote: 'El ser humano es el único animal que tropieza dos veces con la misma piedra.',
    options: ['Aristóteles', 'Platón', 'Séneca', 'Cicerón'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 61,
    quote: 'La felicidad es el sentido y el propósito de la vida.',
    options: ['Aristóteles', 'Platón', 'Epicuro', 'Séneca'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 62,
    quote: 'No hay nada más poderoso que una idea cuyo tiempo ha llegado.',
    options: ['Victor Hugo', 'Voltaire', 'Jean-Paul Sartre', 'Albert Camus'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 63,
    quote: 'El hombre es el ser que existe y es consciente de su existencia.',
    options: ['Jean-Paul Sartre', 'Albert Camus', 'Simone de Beauvoir', 'Maurice Merleau-Ponty'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 64,
    quote: 'Todo lo que es real es racional, y todo lo que es racional es real.',
    options: ['Georg Wilhelm Friedrich Hegel', 'Immanuel Kant', 'Friedrich Nietzsche', 'Arthur Schopenhauer'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 65,
    quote: 'La verdad es la correspondencia entre el pensamiento y la realidad.',
    options: ['Aristóteles', 'Platón', 'Sócrates', 'Parménides'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 66,
    quote: 'No puedo enseñar nada a nadie, solo puedo hacerles pensar.',
    options: ['Sócrates', 'Platón', 'Aristóteles', 'Séneca'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 67,
    quote: 'El mundo es mi representación.',
    options: ['Arthur Schopenhauer', 'Immanuel Kant', 'Friedrich Nietzsche', 'Martin Heidegger'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 68,
    quote: 'La vida es absurda, pero debemos vivirla.',
    options: ['Albert Camus', 'Jean-Paul Sartre', 'Simone de Beauvoir', 'Maurice Merleau-Ponty'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 69,
    quote: 'El tiempo es una ilusión.',
    options: ['Albert Einstein', 'Immanuel Kant', 'Henri Bergson', 'Martin Heidegger'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  {
    id: 70,
    quote: 'La virtud es conocimiento.',
    options: ['Sócrates', 'Platón', 'Aristóteles', 'Epicuro'],
    correctAnswer: 0,
    category: 'Filosofía',
  },
  
  // HISTORIA
  {
    id: 71,
    quote: 'No es más fuerte el que más puede, sino el que más resiste.',
    options: ['Nelson Mandela', 'Martin Luther King', 'Mahatma Gandhi', 'Winston Churchill'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 72,
    quote: 'I have a dream.',
    options: ['Martin Luther King', 'Malcolm X', 'Rosa Parks', 'Barack Obama'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 73,
    quote: 'Sangre, sudor y lágrimas.',
    options: ['Winston Churchill', 'Franklin D. Roosevelt', 'Charles de Gaulle', 'Joseph Stalin'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 74,
    quote: 'La única cosa que debemos temer es al temor mismo.',
    options: ['Franklin D. Roosevelt', 'Winston Churchill', 'Harry Truman', 'Dwight Eisenhower'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 75,
    quote: 'Veni, vidi, vici.',
    options: ['Julio César', 'Augusto', 'Nerón', 'Marco Aurelio'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 76,
    quote: 'Libertad, igualdad, fraternidad.',
    options: ['Revolución Francesa', 'Revolución Americana', 'Revolución Rusa', 'Revolución Industrial'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 77,
    quote: 'El único deber que tenemos con la historia es reescribirla.',
    options: ['Oscar Wilde', 'George Orwell', 'Winston Churchill', 'Mark Twain'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 78,
    quote: 'La historia se repite, primero como tragedia, luego como farsa.',
    options: ['Karl Marx', 'Friedrich Engels', 'Vladimir Lenin', 'Leon Trotsky'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 79,
    quote: 'La historia es la mentira encuadernada.',
    options: ['Napoleón Bonaparte', 'Voltaire', 'Winston Churchill', 'Oscar Wilde'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 80,
    quote: 'Aquí yace un hombre que supo cómo reclutar a su servicio hombres más capaces que él.',
    options: ['Andrew Carnegie', 'John D. Rockefeller', 'Henry Ford', 'Thomas Edison'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 81,
    quote: 'La guerra es la continuación de la política por otros medios.',
    options: ['Carl von Clausewitz', 'Napoleón Bonaparte', 'Sun Tzu', 'Maquiavelo'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 82,
    quote: 'El arte de la guerra es someter al enemigo sin luchar.',
    options: ['Sun Tzu', 'Confucio', 'Lao Tzu', 'Mencius'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 83,
    quote: 'Divide y vencerás.',
    options: ['Julio César', 'Maquiavelo', 'Napoleón Bonaparte', 'Alejandro Magno'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 84,
    quote: 'La democracia es el gobierno del pueblo, por el pueblo y para el pueblo.',
    options: ['Abraham Lincoln', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 85,
    quote: 'No hay nada nuevo bajo el sol, pero sí hay mucho viejo que desconocemos.',
    options: ['Ambrose Bierce', 'Mark Twain', 'Oscar Wilde', 'George Bernard Shaw'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 86,
    quote: 'La historia la escriben los vencedores.',
    options: ['Winston Churchill', 'Napoleón Bonaparte', 'George Orwell', 'Aldous Huxley'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 87,
    quote: 'El pasado es prologo.',
    options: ['William Shakespeare', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 88,
    quote: 'La única forma de lidiar con un mundo no libre es volverte tan absolutamente libre que tu propia existencia sea un acto de rebelión.',
    options: ['Albert Camus', 'Jean-Paul Sartre', 'Simone de Beauvoir', 'George Orwell'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 89,
    quote: 'El poder corrompe, y el poder absoluto corrompe absolutamente.',
    options: ['Lord Acton', 'Winston Churchill', 'Oscar Wilde', 'George Orwell'],
    correctAnswer: 0,
    category: 'Historia',
  },
  {
    id: 90,
    quote: 'La historia es filosofía enseñada con ejemplos.',
    options: ['Dionisio de Halicarnaso', 'Heródoto', 'Tucídides', 'Polibio'],
    correctAnswer: 0,
    category: 'Historia',
  },
  
  // CIENCIA
  {
    id: 91,
    quote: 'Todo lo que sube, baja.',
    options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Leonardo da Vinci'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 92,
    quote: 'E = mc²',
    options: ['Albert Einstein', 'Isaac Newton', 'Max Planck', 'Niels Bohr'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 93,
    quote: 'Y sin embargo se mueve.',
    options: ['Galileo Galilei', 'Isaac Newton', 'Nicolás Copérnico', 'Johannes Kepler'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 94,
    quote: 'La naturaleza aborrece el vacío.',
    options: ['Aristóteles', 'Platón', 'Demócrito', 'Tales de Mileto'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 95,
    quote: 'Dios no juega a los dados.',
    options: ['Albert Einstein', 'Niels Bohr', 'Werner Heisenberg', 'Erwin Schrödinger'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 96,
    quote: 'La verdad es hija del tiempo, no de la autoridad.',
    options: ['Galileo Galilei', 'Isaac Newton', 'Nicolás Copérnico', 'Johannes Kepler'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 97,
    quote: 'Si he visto más lejos es porque estoy parado en los hombros de gigantes.',
    options: ['Isaac Newton', 'Galileo Galilei', 'Johannes Kepler', 'Nicolás Copérnico'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 98,
    quote: 'La ciencia sin religión es coja, la religión sin ciencia es ciega.',
    options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Blaise Pascal'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 99,
    quote: 'El universo no solo es más extraño de lo que imaginamos, es más extraño de lo que podemos imaginar.',
    options: ['J.B.S. Haldane', 'Carl Sagan', 'Stephen Hawking', 'Richard Feynman'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 100,
    quote: 'Somos polvo de estrellas.',
    options: ['Carl Sagan', 'Stephen Hawking', 'Neil deGrasse Tyson', 'Richard Feynman'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 101,
    quote: 'La ciencia es la poesía de la realidad.',
    options: ['Richard Dawkins', 'Carl Sagan', 'Stephen Hawking', 'Neil deGrasse Tyson'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 102,
    quote: 'El principio de incertidumbre: no puedes conocer simultáneamente la posición y el momento de una partícula.',
    options: ['Werner Heisenberg', 'Erwin Schrödinger', 'Niels Bohr', 'Max Planck'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 103,
    quote: 'La vida encontrará un camino.',
    options: ['Jurassic Park (Ian Malcolm)', 'Charles Darwin', 'Richard Dawkins', 'Stephen Jay Gould'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 104,
    quote: 'La evolución es más inteligente que tú.',
    options: ['Richard Dawkins', 'Stephen Jay Gould', 'Charles Darwin', 'Alfred Russel Wallace'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 105,
    quote: 'La curiosidad mató al gato, pero la satisfacción lo trajo de vuelta.',
    options: ['Proverbio científico', 'Richard Feynman', 'Carl Sagan', 'Stephen Hawking'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 106,
    quote: 'No hay nada que temer excepto el miedo mismo, y la radiación.',
    options: ['Marie Curie', 'Albert Einstein', 'Niels Bohr', 'Enrico Fermi'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 107,
    quote: 'La ciencia es un modo de pensar más que un cuerpo de conocimientos.',
    options: ['Carl Sagan', 'Richard Feynman', 'Stephen Hawking', 'Neil deGrasse Tyson'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 108,
    quote: 'El genio es 1% inspiración y 99% transpiración.',
    options: ['Thomas Edison', 'Albert Einstein', 'Isaac Newton', 'Leonardo da Vinci'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 109,
    quote: 'La naturaleza no hace saltos.',
    options: ['Carlos Linneo', 'Charles Darwin', 'Gregor Mendel', 'Louis Pasteur'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  {
    id: 110,
    quote: 'La ciencia es la creencia en la ignorancia de los expertos.',
    options: ['Richard Feynman', 'Carl Sagan', 'Stephen Hawking', 'Albert Einstein'],
    correctAnswer: 0,
    category: 'Ciencia',
  },
  
  // MÚSICA
  {
    id: 111,
    quote: 'La música es el lenguaje universal de la humanidad.',
    options: ['Henry Wadsworth Longfellow', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 112,
    quote: 'Sin música, la vida sería un error.',
    options: ['Friedrich Nietzsche', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Richard Wagner'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 113,
    quote: 'La música es el arte más directo, entra por el oído y va al corazón.',
    options: ['Magdalena Martínez', 'Pablo Casals', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 114,
    quote: 'La música es el vino que llena la copa del silencio.',
    options: ['Robert Fripp', 'David Bowie', 'John Lennon', 'Bob Dylan'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 115,
    quote: 'La música puede cambiar el mundo porque puede cambiar a las personas.',
    options: ['Bono', 'John Lennon', 'Bob Dylan', 'Bob Marley'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 116,
    quote: 'La música es la forma más alta de arte.',
    options: ['Ludwig van Beethoven', 'Richard Wagner', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 117,
    quote: 'La música es el arte que está más cerca de las lágrimas y la memoria.',
    options: ['Oscar Wilde', 'Marcel Proust', 'Virginia Woolf', 'James Joyce'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 118,
    quote: 'La música es el silencio entre las notas.',
    options: ['Claude Debussy', 'Maurice Ravel', 'Igor Stravinsky', 'Pyotr Tchaikovsky'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 119,
    quote: 'La música es mi religión.',
    options: ['Jimi Hendrix', 'Bob Marley', 'John Lennon', 'Kurt Cobain'],
    correctAnswer: 0,
    category: 'Música',
  },
  {
    id: 120,
    quote: 'La música expresa lo que no puede ser dicho y aquello sobre lo que es imposible permanecer en silencio.',
    options: ['Victor Hugo', 'Voltaire', 'Jean-Jacques Rousseau', 'Stendhal'],
    correctAnswer: 0,
    category: 'Música',
  },
  
  // ARTE
  {
    id: 121,
    quote: 'La belleza está en los ojos del que mira.',
    options: ['Oscar Wilde', 'Platón', 'Aristóteles', 'Immanuel Kant'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 122,
    quote: 'El arte es la mentira que nos permite conocer la verdad.',
    options: ['Pablo Picasso', 'Salvador Dalí', 'Vincent van Gogh', 'Henri Matisse'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 123,
    quote: 'La pintura es poesía muda; la poesía, pintura ciega.',
    options: ['Leonardo da Vinci', 'Miguel Ángel', 'Rafael', 'Donatello'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 124,
    quote: 'El arte es la expresión de los sentimientos más profundos del alma.',
    options: ['Vincent van Gogh', 'Pablo Picasso', 'Salvador Dalí', 'Claude Monet'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 125,
    quote: 'La simplicidad es la máxima sofisticación.',
    options: ['Leonardo da Vinci', 'Miguel Ángel', 'Rafael', 'Donatello'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 126,
    quote: 'El arte es la mentira que nos hace darnos cuenta de la verdad.',
    options: ['Pablo Picasso', 'Salvador Dalí', 'Vincent van Gogh', 'Henri Matisse'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 127,
    quote: 'Todo artista fue primero un aficionado.',
    options: ['Ralph Waldo Emerson', 'Henry David Thoreau', 'Walt Whitman', 'Edgar Allan Poe'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 128,
    quote: 'El arte es el placer de un espíritu que penetra en la naturaleza y descubre que también esta tiene alma.',
    options: ['Auguste Rodin', 'Pablo Picasso', 'Vincent van Gogh', 'Henri Matisse'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 129,
    quote: 'La creatividad es la inteligencia divirtiéndose.',
    options: ['Albert Einstein', 'Pablo Picasso', 'Salvador Dalí', 'Leonardo da Vinci'],
    correctAnswer: 0,
    category: 'Arte',
  },
  {
    id: 130,
    quote: 'El arte es la firma de la civilización.',
    options: ['Beverly Sills', 'Maya Angelou', 'Toni Morrison', 'Alice Walker'],
    correctAnswer: 0,
    category: 'Arte',
  },
];

// Categorías disponibles
export const CATEGORIES = [
  'Cine',
  'Literatura',
  'Filosofía',
  'Historia',
  'Ciencia',
  'Música',
  'Arte',
];

