export const QUESTIONS = [
  // CATEGORÍA: FANTASÍA
  {
    id: '1',
    option1: 'Tener la habilidad de hablar con los animales pero que todos te odien',
    option2: 'Ser amado por todos los animales pero no poder comunicarte con ellos',
    category: 'fantasia',
    difficulty: 'medio',
  },
  {
    id: '2',
    option1: 'Ser un vampiro inmortal pero no poder salir nunca al sol',
    option2: 'Ser un lobo hombre que se transforma cada luna llena sin control',
    category: 'fantasia',
    difficulty: 'alto',
  },
  {
    id: '3',
    option1: 'Tener la varita mágica más poderosa del mundo pero no poder hacer hechizos de curación',
    option2: 'Ser el mejor curandero mágico pero no poder usar magia ofensiva',
    category: 'fantasia',
    difficulty: 'medio',
  },
  {
    id: '4',
    option1: 'Vivir en un mundo donde los dragones son mascotas comunes pero son extremadamente destructivos',
    option2: 'Vivir en un mundo sin magia pero con tecnología avanzada',
    category: 'fantasia',
    difficulty: 'medio',
  },
  {
    id: '5',
    option1: 'Poder leer mentes pero escuchar TODOS los pensamientos de TODAS las personas a tu alrededor sin filtro',
    option2: 'Ser completamente invisible pero no poder ver nada mientras lo eres',
    category: 'fantasia',
    difficulty: 'alto',
  },

  // CATEGORÍA: FILOSÓFICO
  {
    id: '6',
    option1: 'Saber la fecha exacta de tu muerte',
    option2: 'Saber la causa exacta de tu muerte, pero no ambas',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '7',
    option1: 'Saber todo sobre el pasado pero nada sobre el futuro',
    option2: 'Saber todo sobre el futuro pero nada sobre el pasado',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '8',
    option1: 'Vivir una vida perfecta pero saber que es una simulación',
    option2: 'Vivir una vida difícil pero saber que es 100% real',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '9',
    option1: 'Saber que el libre albedrío no existe pero poder vivir feliz',
    option2: 'Saber que tienes libre albedrío pero vivir con la ansiedad de cada decisión',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '10',
    option1: 'Ser el último humano en la Tierra pero con todos los recursos',
    option2: 'Ser uno entre 10 billones de humanos viviendo en pobreza extrema',
    category: 'filosofico',
    difficulty: 'alto',
  },

  // CATEGORÍA: CIENCIA FICCIÓN
  {
    id: '11',
    option1: 'Vivir permanentemente en un mundo post-apocalíptico tipo Mad Max',
    option2: 'Vivir en el universo de Wall-E donde los humanos son inútiles y obesos',
    category: 'ciencia-ficcion',
    difficulty: 'medio',
  },
  {
    id: '12',
    option1: 'Ser el único humano en una nave espacial con 1000 androides que se parecen a humanos',
    option2: 'Ser el único androide en una Tierra con 8 mil millones de humanos',
    category: 'ciencia-ficcion',
    difficulty: 'medio',
  },
  {
    id: '13',
    option1: 'Poder viajar en el tiempo pero solo hacia atrás',
    option2: 'Poder viajar en el tiempo pero solo hacia adelante',
    category: 'ciencia-ficcion',
    difficulty: 'medio',
  },
  {
    id: '14',
    option1: 'Tener un clon perfecto tuyo que vive tu vida mejor que tú',
    option2: 'Ser el clon de alguien más y saber que no eres el original',
    category: 'ciencia-ficcion',
    difficulty: 'alto',
  },
  {
    id: '15',
    option1: 'Vivir en Marte con la mejor tecnología pero sin poder volver nunca a la Tierra',
    option2: 'Quedarte en la Tierra que se está destruyendo pero estar con tu familia',
    category: 'ciencia-ficcion',
    difficulty: 'medio',
  },

  // CATEGORÍA: MORAL
  {
    id: '16',
    option1: 'Tener que decir siempre la verdad sin filtro',
    option2: 'Tener que mentir en cada frase que digas',
    category: 'moral',
    difficulty: 'medio',
  },
  {
    id: '17',
    option1: 'Salvar a 100 desconocidos matando a 1 persona inocente',
    option2: 'No hacer nada y dejar que mueran las 100 personas',
    category: 'moral',
    difficulty: 'alto',
  },
  {
    id: '18',
    option1: 'Ser famoso y admirado por todos pero saber que eres una persona horrible',
    option2: 'Ser desconocido pero saber que eres una buena persona',
    category: 'moral',
    difficulty: 'medio',
  },
  {
    id: '19',
    option1: 'Poder ver todos los secretos de las personas pero no poder hacer nada al respecto',
    option2: 'No poder saber nada sobre nadie pero vivir en paz',
    category: 'moral',
    difficulty: 'medio',
  },
  {
    id: '20',
    option1: 'Ganar el poder de cambiar el mundo pero perder toda tu humanidad',
    option2: 'Mantener tu humanidad pero no poder cambiar nada',
    category: 'moral',
    difficulty: 'alto',
  },

  // CATEGORÍA: SUPERPODERES
  {
    id: '21',
    option1: 'Poder rebobinar 10 segundos en tu vida en cualquier momento',
    option2: 'Poder pausar el tiempo para todos menos para ti durante 10 segundos una vez al día',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '22',
    option1: 'Poder volar pero solo a 10 cm del suelo',
    option2: 'Poder nadar pero solo en agua sucia',
    category: 'superpoderes',
    difficulty: 'bajo',
  },
  {
    id: '23',
    option1: 'Ser invisible pero hacer ruido con cada paso',
    option2: 'Ser completamente silencioso pero muy visible (brillante)',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '24',
    option1: 'Tener superfuerza pero no poder controlarla (rompes todo que tocas)',
    option2: 'Tener súper velocidad pero solo en círculos pequeños',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '25',
    option1: 'Poder teletransportarte pero solo a lugares donde hay baños públicos',
    option2: 'Poder cambiar de forma pero solo a animales domésticos',
    category: 'superpoderes',
    difficulty: 'bajo',
  },

  // CATEGORÍA: ABSURDO
  {
    id: '26',
    option1: 'Que cada canción que escuches se convierta en "Baby Shark" a mitad',
    option2: 'Que cada película que veas tenga a Jar Jar Binks añadido digitalmente en cada escena',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '27',
    option1: 'Tener dedos de los pies tan largos como los dedos de tus manos',
    option2: 'Tener dedos de las manos tan cortos como los de tus pies',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '28',
    option1: 'Luchar contra un pato del tamaño de un caballo',
    option2: 'Luchar contra cien caballos del tamaño de un pato',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '29',
    option1: 'Tener que usar ropa interior de papel',
    option2: 'Tener que usar calcetines de papel',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '30',
    option1: 'Tener que estornudar cada vez que alguien dice "salud"',
    option2: 'Tener que decir "gracias" cada vez que alguien estornuda',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '31',
    option1: 'Tener pies tan grandes que no puedes comprar zapatos',
    option2: 'Tener pies tan pequeños que siempre se te caen los zapatos',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '32',
    option1: 'Tener que cantar todo lo que piensas en voz alta',
    option2: 'Tener que bailar cada vez que escuchas música',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '33',
    option1: 'Ser alérgico al agua pero solo los martes',
    option2: 'Ser alérgico al aire pero solo los jueves',
    category: 'absurdo',
    difficulty: 'bajo',
  },

  // CATEGORÍA: COMIDA
  {
    id: '34',
    option1: 'Comer solo pizza durante toda tu vida',
    option2: 'Nunca poder volver a comer pizza',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '35',
    option1: 'Tener que comer insectos en cada comida',
    option2: 'Tener que dormir en el suelo toda tu vida',
    category: 'comida',
    difficulty: 'medio',
  },
  {
    id: '36',
    option1: 'Comer la comida más deliciosa del mundo pero siempre está fría',
    option2: 'Comer comida normal pero siempre está perfectamente caliente',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '37',
    option1: 'Tener que comer solo comida picante el resto de tu vida',
    option2: 'Nunca poder probar nada con sabor',
    category: 'comida',
    difficulty: 'medio',
  },
  {
    id: '38',
    option1: 'Poder comer todo lo que quieras sin engordar pero todo sabe a cartón',
    option2: 'Tener que hacer dieta estricta pero todo sabe increíble',
    category: 'comida',
    difficulty: 'medio',
  },

  // CATEGORÍA: TECNOLOGÍA
  {
    id: '39',
    option1: 'Tener WiFi ilimitado pero sin batería en ningún dispositivo',
    option2: 'Tener batería infinita pero sin conexión a Internet',
    category: 'tecnologia',
    difficulty: 'medio',
  },
  {
    id: '40',
    option1: 'Tener el teléfono más avanzado pero solo puedes usarlo 1 hora al día',
    option2: 'Tener un teléfono antiguo pero puedes usarlo las 24 horas',
    category: 'tecnologia',
    difficulty: 'bajo',
  },
  {
    id: '41',
    option1: 'Vivir en una casa inteligente controlada por IA que a veces toma decisiones por ti',
    option2: 'Vivir sin tecnología moderna pero con total control sobre tu vida',
    category: 'tecnologia',
    difficulty: 'medio',
  },
  {
    id: '42',
    option1: 'Tener acceso a Internet pero solo puedes ver contenido de hace 10 años',
    option2: 'Tener acceso a contenido nuevo pero sin poder buscar nada',
    category: 'tecnologia',
    difficulty: 'medio',
  },

  // CATEGORÍA: INCÓMODO
  {
    id: '43',
    option1: 'Tener que usar ropa mojada todo el día',
    option2: 'Tener que usar zapatos 3 tallas más pequeños',
    category: 'incomodo',
    difficulty: 'medio',
  },
  {
    id: '44',
    option1: 'Tener que rascarte constantemente pero no puedes hacerlo en público',
    option2: 'Tener que bostezar cada 5 minutos sin poder parar',
    category: 'incomodo',
    difficulty: 'medio',
  },
  {
    id: '45',
    option1: 'Tener que sentarte siempre en asientos incómodos',
    option2: 'Tener que caminar siempre sobre piedras pequeñas',
    category: 'incomodo',
    difficulty: 'bajo',
  },
  {
    id: '46',
    option1: 'Tener que usar ropa de tu tamaño pero del género opuesto',
    option2: 'Tener que usar ropa 5 tallas más grande toda tu vida',
    category: 'incomodo',
    difficulty: 'bajo',
  },

  // CATEGORÍA: RELACIONES
  {
    id: '47',
    option1: 'Estar en una relación perfecta pero saber que tu pareja es un robot',
    option2: 'Estar en una relación difícil pero saber que es 100% humana',
    category: 'relaciones',
    difficulty: 'alto',
  },
  {
    id: '48',
    option1: 'Ser amado por todos pero no poder amar a nadie',
    option2: 'Amar profundamente pero no ser amado por nadie',
    category: 'relaciones',
    difficulty: 'alto',
  },
  {
    id: '49',
    option1: 'Tener que decir "te quiero" a todos cada vez que los ves',
    option2: 'Nunca poder decir "te quiero" a nadie aunque lo sientas',
    category: 'relaciones',
    difficulty: 'medio',
  },
  {
    id: '50',
    option1: 'Saber todo sobre tu pareja ideal pero nunca conocerla',
    option2: 'Conocer a tu pareja ideal pero no poder estar juntos',
    category: 'relaciones',
    difficulty: 'alto',
  },

  // CATEGORÍA: TRABAJO/DINERO
  {
    id: '51',
    option1: 'Trabajar en tu trabajo soñado pero ganar muy poco dinero',
    option2: 'Trabajar en un trabajo horrible pero ganar millones',
    category: 'trabajo',
    difficulty: 'medio',
  },
  {
    id: '52',
    option1: 'Ser rico pero tener que trabajar 80 horas a la semana',
    option2: 'Ser pobre pero tener todo el tiempo libre del mundo',
    category: 'trabajo',
    difficulty: 'medio',
  },
  {
    id: '53',
    option1: 'Tener el trabajo perfecto pero todos tus compañeros te odian',
    option2: 'Tener compañeros perfectos pero odiar tu trabajo',
    category: 'trabajo',
    difficulty: 'medio',
  },
  {
    id: '54',
    option1: 'Ser famoso y rico pero sin privacidad alguna',
    option2: 'Ser completamente anónimo pero vivir en la pobreza',
    category: 'trabajo',
    difficulty: 'medio',
  },

  // CATEGORÍA: SALUD
  {
    id: '55',
    option1: 'Vivir 200 años pero con mala salud constante',
    option2: 'Vivir 50 años pero con perfecta salud',
    category: 'salud',
    difficulty: 'alto',
  },
  {
    id: '56',
    option1: 'Tener un dolor de cabeza constante pero leve',
    option2: 'Tener dolores intensos pero solo una vez al mes',
    category: 'salud',
    difficulty: 'medio',
  },
  {
    id: '57',
    option1: 'Ser inmune a todas las enfermedades pero envejecer el doble de rápido',
    option2: 'Envejecer muy lentamente pero ser propenso a todas las enfermedades',
    category: 'salud',
    difficulty: 'medio',
  },
  {
    id: '58',
    option1: 'Tener memoria perfecta pero recordar todos los malos momentos',
    option2: 'Tener mala memoria pero solo recordar los buenos momentos',
    category: 'salud',
    difficulty: 'medio',
  },

  // CATEGORÍA: SOCIAL
  {
    id: '59',
    option1: 'Ser el alma de la fiesta pero tener que hacerlo siempre',
    option2: 'Ser tímido e introvertido pero poder estar solo cuando quieras',
    category: 'social',
    difficulty: 'medio',
  },
  {
    id: '60',
    option1: 'Tener que saludar a todos con un beso en la mejilla siempre',
    option2: 'Nunca poder saludar a nadie físicamente',
    category: 'social',
    difficulty: 'bajo',
  },
  {
    id: '61',
    option1: 'Ser la persona más popular pero sin amigos verdaderos',
    option2: 'Tener pocos amigos pero todos son verdaderos',
    category: 'social',
    difficulty: 'medio',
  },
  {
    id: '62',
    option1: 'Tener que hablar en público cada día pero hacerlo mal',
    option2: 'Ser excelente hablando en público pero nunca poder hacerlo',
    category: 'social',
    difficulty: 'medio',
  },

  // MÁS PREGUNTAS EXTREMAS
  {
    id: '63',
    option1: 'Vivir en un mundo donde siempre es de noche',
    option2: 'Vivir en un mundo donde siempre es de día',
    category: 'filosofico',
    difficulty: 'medio',
  },
  {
    id: '64',
    option1: 'Tener que beber solo café por el resto de tu vida',
    option2: 'Nunca poder beber café de nuevo',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '65',
    option1: 'Poder entender todos los idiomas pero no poder hablarlos',
    option2: 'Poder hablar todos los idiomas pero no entenderlos',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '66',
    option1: 'Tener que usar gafas de sol dentro de los edificios',
    option2: 'Tener que usar gafas normales al aire libre',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '67',
    option1: 'Ser el mejor en todo pero saber que es por trampas',
    option2: 'Ser el peor en todo pero saber que siempre das tu mejor esfuerzo',
    category: 'moral',
    difficulty: 'alto',
  },
  {
    id: '68',
    option1: 'Tener que dormir 20 horas al día',
    option2: 'Solo poder dormir 2 horas al día',
    category: 'salud',
    difficulty: 'medio',
  },
  {
    id: '69',
    option1: 'Poder ver el futuro pero no poder cambiarlo',
    option2: 'No poder ver el futuro pero tener control total sobre él',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '70',
    option1: 'Tener que vivir en un lugar donde siempre hace frío extremo',
    option2: 'Tener que vivir en un lugar donde siempre hace calor extremo',
    category: 'incomodo',
    difficulty: 'medio',
  },
  {
    id: '71',
    option1: 'Ser el único humano que puede ver colores',
    option2: 'Ser el único humano que ve en blanco y negro',
    category: 'fantasia',
    difficulty: 'medio',
  },
  {
    id: '72',
    option1: 'Tener que comer solo con palillos chinos',
    option2: 'Tener que comer solo con las manos',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '73',
    option1: 'Poder teletransportarte pero solo a lugares que has visitado antes',
    option2: 'Poder volar pero solo a lugares que nunca has visto',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '74',
    option1: 'Tener que usar el mismo outfit todos los días',
    option2: 'Tener que cambiar de ropa cada hora',
    category: 'incomodo',
    difficulty: 'bajo',
  },
  {
    id: '75',
    option1: 'Ser capaz de curar a otros pero enfermarte cada vez que lo haces',
    option2: 'Tener salud perfecta pero no poder ayudar a nadie',
    category: 'moral',
    difficulty: 'alto',
  },
  {
    id: '76',
    option1: 'Vivir en una ciudad donde todos caminan al revés',
    option2: 'Vivir en una ciudad donde todos hablan al revés',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '77',
    option1: 'Tener que ver todas las películas desde el final',
    option2: 'Tener que leer todos los libros desde el último capítulo',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '78',
    option1: 'Poder escuchar los pensamientos de las plantas',
    option2: 'Poder escuchar los pensamientos de las piedras',
    category: 'fantasia',
    difficulty: 'bajo',
  },
  {
    id: '79',
    option1: 'Tener que dar 3 vueltas antes de entrar a cualquier habitación',
    option2: 'Tener que tocar la puerta exactamente 7 veces antes de entrar',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '80',
    option1: 'Ser capaz de ver a través de las paredes pero no de ver normalmente',
    option2: 'Tener visión normal pero no poder ver a través de nada transparente',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '81',
    option1: 'Tener que contar cada paso que das en voz alta',
    option2: 'Tener que cantar cada palabra que dices',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '82',
    option1: 'Vivir en un mundo donde el dinero crece en árboles',
    option2: 'Vivir en un mundo donde la comida es gratis pero el aire cuesta dinero',
    category: 'filosofico',
    difficulty: 'medio',
  },
  {
    id: '83',
    option1: 'Tener que dormir de pie como un caballo',
    option2: 'Tener que dormir flotando en agua',
    category: 'incomodo',
    difficulty: 'medio',
  },
  {
    id: '84',
    option1: 'Poder hablar con los muertos pero solo los que no conociste',
    option2: 'Poder hablar con los vivos pero solo los que nunca conocerás',
    category: 'fantasia',
    difficulty: 'medio',
  },
  {
    id: '85',
    option1: 'Tener que escribir todo con la mano no dominante',
    option2: 'Tener que escribir todo al revés',
    category: 'incomodo',
    difficulty: 'bajo',
  },
  {
    id: '86',
    option1: 'Ser capaz de entender a los bebés pero no a los adultos',
    option2: 'Ser capaz de entender a los animales pero no a los humanos',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '87',
    option1: 'Tener que usar solo una mano para todo durante un año',
    option2: 'Tener que usar solo un pie para caminar durante un año',
    category: 'incomodo',
    difficulty: 'medio',
  },
  {
    id: '88',
    option1: 'Poder controlar el clima pero solo en tu casa',
    option2: 'Poder controlar el clima del mundo pero no de tu casa',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '89',
    option1: 'Vivir en un mundo donde todos tienen tu misma cara',
    option2: 'Vivir en un mundo donde cambias de cara cada día',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '90',
    option1: 'Tener que comer solo alimentos azules',
    option2: 'Tener que comer solo alimentos verdes',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '91',
    option1: 'Ser capaz de volar pero solo hacia arriba',
    option2: 'Ser capaz de volar pero solo hacia abajo',
    category: 'superpoderes',
    difficulty: 'bajo',
  },
  {
    id: '92',
    option1: 'Tener que decir la hora en voz alta cada hora',
    option2: 'Tener que contar las estrellas cada noche',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '93',
    option1: 'Poder duplicar cualquier objeto pero solo una vez al día',
    option2: 'Poder crear objetos de la nada pero solo objetos inútiles',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '94',
    option1: 'Vivir en una realidad donde eres el personaje principal',
    option2: 'Vivir en una realidad donde eres un extra en la vida de otros',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '95',
    option1: 'Tener que reírte cada vez que alguien estornuda',
    option2: 'Tener que llorar cada vez que alguien sonríe',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '96',
    option1: 'Ser capaz de sentir las emociones de todos a tu alrededor',
    option2: 'No poder sentir emociones propias pero entenderlas en otros',
    category: 'moral',
    difficulty: 'alto',
  },
  {
    id: '97',
    option1: 'Tener que caminar siempre de espaldas',
    option2: 'Tener que hablar siempre de espaldas a la persona',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '98',
    option1: 'Poder cambiar tu edad pero solo una vez en la vida',
    option2: 'Poder cambiar tu género pero solo una vez en la vida',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '99',
    option1: 'Vivir en un mundo donde la gravedad funciona al revés',
    option2: 'Vivir en un mundo donde el tiempo corre al revés',
    category: 'ciencia-ficcion',
    difficulty: 'medio',
  },
  {
    id: '100',
    option1: 'Tener que hacer una reverencia antes de hablar con alguien',
    option2: 'Tener que hacer una voltereta antes de entrar a cualquier lugar',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '101',
    option1: 'Ser capaz de ver en la oscuridad pero no a plena luz',
    option2: 'Ser capaz de ver perfectamente con luz pero quedar ciego en la oscuridad',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '102',
    option1: 'Tener que comer con los ojos cerrados siempre',
    option2: 'Tener que comer con tapones en los oídos siempre',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '103',
    option1: 'Poder mover objetos con la mente pero solo objetos de menos de 10 gramos',
    option2: 'Poder mover objetos muy pesados pero solo con contacto físico',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '104',
    option1: 'Vivir en un mundo donde cada día es lunes',
    option2: 'Vivir en un mundo donde cada día es viernes por la noche',
    category: 'filosofico',
    difficulty: 'medio',
  },
  {
    id: '105',
    option1: 'Tener que saludar a todos con un apretón de manos de 30 segundos',
    option2: 'Tener que abrazar a todos durante 1 minuto',
    category: 'social',
    difficulty: 'medio',
  },
  {
    id: '106',
    option1: 'Ser capaz de oler el futuro',
    option2: 'Ser capaz de saborear el pasado',
    category: 'fantasia',
    difficulty: 'bajo',
  },
  {
    id: '107',
    option1: 'Tener que vestirte según el estado de ánimo del día anterior',
    option2: 'Tener que vestirte según el clima del día siguiente',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '108',
    option1: 'Poder regenerar cualquier parte del cuerpo excepto el cerebro',
    option2: 'Tener un cerebro perfecto pero cuerpo frágil',
    category: 'salud',
    difficulty: 'alto',
  },
  {
    id: '109',
    option1: 'Vivir en una casa que cambia de color según tu estado de ánimo',
    option2: 'Vivir en una casa que habla y da consejos constantemente',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '110',
    option1: 'Tener que recitar un poema antes de comer',
    option2: 'Tener que cantar una canción antes de dormir',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '111',
    option1: 'Ser capaz de comunicarte solo mediante emojis',
    option2: 'Ser capaz de comunicarte solo mediante gestos exagerados',
    category: 'social',
    difficulty: 'medio',
  },
  {
    id: '112',
    option1: 'Tener que beber agua salada toda tu vida',
    option2: 'Tener que beber solo jugo de limón toda tu vida',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '113',
    option1: 'Poder viajar a cualquier país pero solo por 1 hora',
    option2: 'Poder viajar solo a 1 país pero quedarte el tiempo que quieras',
    category: 'superpoderes',
    difficulty: 'medio',
  },
  {
    id: '114',
    option1: 'Vivir en un mundo donde todos tienen superpoderes menos tú',
    option2: 'Vivir en un mundo donde solo tú tienes superpoderes',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '115',
    option1: 'Tener que hacer ejercicio cada vez que piensas en comida',
    option2: 'Tener que comer cada vez que piensas en ejercicio',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '116',
    option1: 'Ser capaz de leer libros completos en 1 segundo pero no recordar nada',
    option2: 'Leer muy lento pero recordar cada palabra para siempre',
    category: 'salud',
    difficulty: 'medio',
  },
  {
    id: '117',
    option1: 'Tener que vivir según las reglas de un juego de mesa',
    option2: 'Tener que vivir según las reglas de un videojuego',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '118',
    option1: 'Poder controlar tus sueños pero no poder soñar libremente',
    option2: 'Soñar libremente pero sin control sobre los sueños',
    category: 'fantasia',
    difficulty: 'medio',
  },
  {
    id: '119',
    option1: 'Vivir en un mundo donde el dinero se mide en horas de sueño',
    option2: 'Vivir en un mundo donde el tiempo se mide en dinero',
    category: 'filosofico',
    difficulty: 'medio',
  },
  {
    id: '120',
    option1: 'Tener que usar siempre ropa de payaso',
    option2: 'Tener que usar siempre ropa de gala formal',
    category: 'incomodo',
    difficulty: 'bajo',
  },
  {
    id: '121',
    option1: 'Ser capaz de entender todos los chistes pero nunca reírte',
    option2: 'Reírte de todo pero nunca entender los chistes',
    category: 'absurdo',
    difficulty: 'bajo',
  },
  {
    id: '122',
    option1: 'Tener que comer solo cosas que empiecen con la letra A',
    option2: 'Tener que comer solo cosas que terminen con la letra Z',
    category: 'comida',
    difficulty: 'bajo',
  },
  {
    id: '123',
    option1: 'Poder hablar con las máquinas pero no con las personas',
    option2: 'Poder hablar con las personas pero no con las máquinas',
    category: 'tecnologia',
    difficulty: 'medio',
  },
  {
    id: '124',
    option1: 'Vivir en una ciudad donde todos los edificios son transparentes',
    option2: 'Vivir en una ciudad donde todos los edificios son espejos',
    category: 'ciencia-ficcion',
    difficulty: 'medio',
  },
  {
    id: '125',
    option1: 'Tener que contar hasta 100 antes de hacer cualquier decisión importante',
    option2: 'Tener que tomar todas las decisiones en menos de 1 segundo',
    category: 'moral',
    difficulty: 'medio',
  },
  {
    id: '126',
    option1: 'Ser capaz de sentir el dolor físico de otros',
    option2: 'Ser incapaz de sentir tu propio dolor físico',
    category: 'moral',
    difficulty: 'alto',
  },
  {
    id: '127',
    option1: 'Tener que vivir cada día como si fuera tu último',
    option2: 'Tener que vivir cada día como si fueras inmortal',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '128',
    option1: 'Poder controlar la velocidad de tu envejecimiento',
    option2: 'Poder controlar la velocidad del tiempo a tu alrededor',
    category: 'superpoderes',
    difficulty: 'alto',
  },
  {
    id: '129',
    option1: 'Vivir en un mundo donde las emociones tienen colores visibles',
    option2: 'Vivir en un mundo donde los pensamientos son audibles',
    category: 'filosofico',
    difficulty: 'alto',
  },
  {
    id: '130',
    option1: 'Tener que hacer una promesa antes de cada comida',
    option2: 'Tener que hacer un juramento antes de cada conversación',
    category: 'absurdo',
    difficulty: 'bajo',
  },
];

// Categorías disponibles para filtrado
export const CATEGORIES = [
  { id: 'fantasia', name: 'Fantasía', icon: '✨' },
  { id: 'filosofico', name: 'Filosófico', icon: '🤔' },
  { id: 'ciencia-ficcion', name: 'Ciencia Ficción', icon: '🚀' },
  { id: 'moral', name: 'Moral', icon: '⚖️' },
  { id: 'superpoderes', name: 'Superpoderes', icon: '🦸' },
  { id: 'absurdo', name: 'Absurdo', icon: '🤪' },
  { id: 'comida', name: 'Comida', icon: '🍕' },
  { id: 'tecnologia', name: 'Tecnología', icon: '💻' },
  { id: 'incomodo', name: 'Incómodo', icon: '😣' },
  { id: 'relaciones', name: 'Relaciones', icon: '💕' },
  { id: 'trabajo', name: 'Trabajo', icon: '💼' },
  { id: 'salud', name: 'Salud', icon: '🏥' },
  { id: 'social', name: 'Social', icon: '👥' },
];

// Modos de juego
export const GAME_MODES = [
  { id: 'normal', name: 'Normal', description: 'Preguntas aleatorias de todas las categorías' },
  { id: 'fiesta', name: 'Fiesta', description: 'Preguntas divertidas y absurdas' },
  { id: 'profundo', name: 'Profundo', description: 'Preguntas filosóficas y morales' },
  { id: 'extremo', name: 'Extremo', description: 'Solo las preguntas más extremas' },
  { id: 'rapido', name: 'Rápido', description: 'Preguntas fáciles y rápidas' },
];

