// Lista de ubicaciones para Geoguessr de Salón
// Cada ubicación tiene: id, name, imageUrl, country, city, coordinates, continent, hints

export const LOCATIONS = [
  // EUROPA
  {
    id: 'paris-france',
    name: 'París, Francia',
    imageUrl: 'https://via.placeholder.com/800x600/4a90e2/ffffff?text=Paris+France',
    country: 'Francia',
    city: 'París',
    continent: 'Europa',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    hints: ['Ciudad de la luz', 'Torre Eiffel', 'Río Sena', 'Capital de Francia'],
  },
  {
    id: 'london-uk',
    name: 'Londres, Reino Unido',
    imageUrl: 'https://via.placeholder.com/800x600/2c3e50/ffffff?text=London+UK',
    country: 'Reino Unido',
    city: 'Londres',
    continent: 'Europa',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    hints: ['Big Ben', 'Támesis', 'Lluvia frecuente', 'Capital del Reino Unido'],
  },
  {
    id: 'rome-italy',
    name: 'Roma, Italia',
    imageUrl: 'https://via.placeholder.com/800x600/e74c3c/ffffff?text=Rome+Italy',
    country: 'Italia',
    city: 'Roma',
    continent: 'Europa',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    hints: ['Coliseo', 'Ciudad eterna', 'Vaticano', 'Capital de Italia'],
  },
  {
    id: 'barcelona-spain',
    name: 'Barcelona, España',
    imageUrl: 'https://via.placeholder.com/800x600/f39c12/ffffff?text=Barcelona+Spain',
    country: 'España',
    city: 'Barcelona',
    continent: 'Europa',
    coordinates: { lat: 41.3851, lng: 2.1734 },
    hints: ['Sagrada Familia', 'Gaudí', 'Mediterráneo', 'Cataluña'],
  },
  {
    id: 'madrid-spain',
    name: 'Madrid, España',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=Madrid+Spain',
    country: 'España',
    city: 'Madrid',
    continent: 'Europa',
    coordinates: { lat: 40.4168, lng: -3.7038 },
    hints: ['Prado', 'Capital de España', 'Plaza Mayor', 'Real Madrid'],
  },
  {
    id: 'amsterdam-netherlands',
    name: 'Ámsterdam, Países Bajos',
    imageUrl: 'https://via.placeholder.com/800x600/3498db/ffffff?text=Amsterdam+Netherlands',
    country: 'Países Bajos',
    city: 'Ámsterdam',
    continent: 'Europa',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    hints: ['Canales', 'Tulipanes', 'Bicicletas', 'Museo Van Gogh'],
  },
  {
    id: 'berlin-germany',
    name: 'Berlín, Alemania',
    imageUrl: 'https://via.placeholder.com/800x600/34495e/ffffff?text=Berlin+Germany',
    country: 'Alemania',
    city: 'Berlín',
    continent: 'Europa',
    coordinates: { lat: 52.5200, lng: 13.4050 },
    hints: ['Muro de Berlín', 'Puerta de Brandeburgo', 'Capital de Alemania', 'Río Spree'],
  },
  {
    id: 'vienna-austria',
    name: 'Viena, Austria',
    imageUrl: 'https://via.placeholder.com/800x600/16a085/ffffff?text=Vienna+Austria',
    country: 'Austria',
    city: 'Viena',
    continent: 'Europa',
    coordinates: { lat: 48.2082, lng: 16.3738 },
    hints: ['Música clásica', 'Cafés', 'Danubio', 'Capital de Austria'],
  },
  {
    id: 'prague-czech',
    name: 'Praga, República Checa',
    imageUrl: 'https://via.placeholder.com/800x600/e67e22/ffffff?text=Prague+Czech',
    country: 'República Checa',
    city: 'Praga',
    continent: 'Europa',
    coordinates: { lat: 50.0755, lng: 14.4378 },
    hints: ['Reloj astronómico', 'Puente de Carlos', 'Cerveza', 'Capital checa'],
  },
  {
    id: 'athens-greece',
    name: 'Atenas, Grecia',
    imageUrl: 'https://via.placeholder.com/800x600/f1c40f/ffffff?text=Athens+Greece',
    country: 'Grecia',
    city: 'Atenas',
    continent: 'Europa',
    coordinates: { lat: 37.9838, lng: 23.7275 },
    hints: ['Acrópolis', 'Partenón', 'Capital de Grecia', 'Cuna de la democracia'],
  },
  {
    id: 'stockholm-sweden',
    name: 'Estocolmo, Suecia',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Stockholm+Sweden',
    country: 'Suecia',
    city: 'Estocolmo',
    continent: 'Europa',
    coordinates: { lat: 59.3293, lng: 18.0686 },
    hints: ['Islas', 'Capital de Suecia', 'Nobel', 'Archipiélago'],
  },
  {
    id: 'oslo-norway',
    name: 'Oslo, Noruega',
    imageUrl: 'https://via.placeholder.com/800x600/8e44ad/ffffff?text=Oslo+Norway',
    country: 'Noruega',
    city: 'Oslo',
    continent: 'Europa',
    coordinates: { lat: 59.9139, lng: 10.7522 },
    hints: ['Fjord', 'Capital de Noruega', 'Aurora boreal', 'Naturaleza'],
  },
  {
    id: 'copenhagen-denmark',
    name: 'Copenhague, Dinamarca',
    imageUrl: 'https://via.placeholder.com/800x600/2980b9/ffffff?text=Copenhagen+Denmark',
    country: 'Dinamarca',
    city: 'Copenhague',
    continent: 'Europa',
    coordinates: { lat: 55.6761, lng: 12.5683 },
    hints: ['Sirena', 'Bicicletas', 'Capital de Dinamarca', 'Hygge'],
  },
  {
    id: 'warsaw-poland',
    name: 'Varsovia, Polonia',
    imageUrl: 'https://via.placeholder.com/800x600/c0392b/ffffff?text=Warsaw+Poland',
    country: 'Polonia',
    city: 'Varsovia',
    continent: 'Europa',
    coordinates: { lat: 52.2297, lng: 21.0122 },
    hints: ['Vístula', 'Capital de Polonia', 'Reconstruida', 'Chopin'],
  },
  {
    id: 'budapest-hungary',
    name: 'Budapest, Hungría',
    imageUrl: 'https://via.placeholder.com/800x600/d35400/ffffff?text=Budapest+Hungary',
    country: 'Hungría',
    city: 'Budapest',
    continent: 'Europa',
    coordinates: { lat: 47.4979, lng: 19.0402 },
    hints: ['Danubio', 'Baños termales', 'Capital de Hungría', 'Parlamento'],
  },
  {
    id: 'lisbon-portugal',
    name: 'Lisboa, Portugal',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Lisbon+Portugal',
    country: 'Portugal',
    city: 'Lisboa',
    continent: 'Europa',
    coordinates: { lat: 38.7223, lng: -9.1393 },
    hints: ['Tranvías', 'Capital de Portugal', 'Tajo', 'Fado'],
  },
  {
    id: 'dublin-ireland',
    name: 'Dublín, Irlanda',
    imageUrl: 'https://via.placeholder.com/800x600/16a085/ffffff?text=Dublin+Ireland',
    country: 'Irlanda',
    city: 'Dublín',
    continent: 'Europa',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    hints: ['Guinness', 'Capital de Irlanda', 'Liffey', 'Tréboles'],
  },
  {
    id: 'edinburgh-scotland',
    name: 'Edimburgo, Escocia',
    imageUrl: 'https://via.placeholder.com/800x600/34495e/ffffff?text=Edinburgh+Scotland',
    country: 'Reino Unido',
    city: 'Edimburgo',
    continent: 'Europa',
    coordinates: { lat: 55.9533, lng: -3.1883 },
    hints: ['Castillo', 'Festival', 'Whisky', 'Capital de Escocia'],
  },
  {
    id: 'brussels-belgium',
    name: 'Bruselas, Bélgica',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=Brussels+Belgium',
    country: 'Bélgica',
    city: 'Bruselas',
    continent: 'Europa',
    coordinates: { lat: 50.8503, lng: 4.3517 },
    hints: ['Chocolate', 'Capital de Bélgica', 'UE', 'Atomium'],
  },
  {
    id: 'zurich-switzerland',
    name: 'Zúrich, Suiza',
    imageUrl: 'https://via.placeholder.com/800x600/3498db/ffffff?text=Zurich+Switzerland',
    country: 'Suiza',
    city: 'Zúrich',
    continent: 'Europa',
    coordinates: { lat: 47.3769, lng: 8.5417 },
    hints: ['Bancos', 'Alpes', 'Relojes', 'Lago'],
  },
  {
    id: 'moscow-russia',
    name: 'Moscú, Rusia',
    imageUrl: 'https://via.placeholder.com/800x600/e74c3c/ffffff?text=Moscow+Russia',
    country: 'Rusia',
    city: 'Moscú',
    continent: 'Europa',
    coordinates: { lat: 55.7558, lng: 37.6173 },
    hints: ['Kremlin', 'Capital de Rusia', 'Plaza Roja', 'Muy frío'],
  },
  {
    id: 'istanbul-turkey',
    name: 'Estambul, Turquía',
    imageUrl: 'https://via.placeholder.com/800x600/f39c12/ffffff?text=Istanbul+Turkey',
    country: 'Turquía',
    city: 'Estambul',
    continent: 'Europa',
    coordinates: { lat: 41.0082, lng: 28.9784 },
    hints: ['Bósforo', 'Hagia Sophia', 'Dos continentes', 'Bazar'],
  },
  {
    id: 'helsinki-finland',
    name: 'Helsinki, Finlandia',
    imageUrl: 'https://via.placeholder.com/800x600/2c3e50/ffffff?text=Helsinki+Finland',
    country: 'Finlandia',
    city: 'Helsinki',
    continent: 'Europa',
    coordinates: { lat: 60.1699, lng: 24.9384 },
    hints: ['Saunas', 'Capital de Finlandia', 'Nokia', 'Islas'],
  },
  {
    id: 'reykjavik-iceland',
    name: 'Reikiavik, Islandia',
    imageUrl: 'https://via.placeholder.com/800x600/16a085/ffffff?text=Reykjavik+Iceland',
    country: 'Islandia',
    city: 'Reikiavik',
    continent: 'Europa',
    coordinates: { lat: 64.1466, lng: -21.9426 },
    hints: ['Geiseres', 'Capital de Islandia', 'Aurora', 'Volcanes'],
  },
  
  // ASIA
  {
    id: 'tokyo-japan',
    name: 'Tokio, Japón',
    imageUrl: 'https://via.placeholder.com/800x600/e74c3c/ffffff?text=Tokyo+Japan',
    country: 'Japón',
    city: 'Tokio',
    continent: 'Asia',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    hints: ['Sushi', 'Capital de Japón', 'Sakura', 'Tecnología'],
  },
  {
    id: 'beijing-china',
    name: 'Pekín, China',
    imageUrl: 'https://via.placeholder.com/800x600/2c3e50/ffffff?text=Beijing+China',
    country: 'China',
    city: 'Pekín',
    continent: 'Asia',
    coordinates: { lat: 39.9042, lng: 116.4074 },
    hints: ['Gran Muralla', 'Capital de China', 'Ciudad Prohibida', 'Pekín'],
  },
  {
    id: 'shanghai-china',
    name: 'Shanghái, China',
    imageUrl: 'https://via.placeholder.com/800x600/3498db/ffffff?text=Shanghai+China',
    country: 'China',
    city: 'Shanghái',
    continent: 'Asia',
    coordinates: { lat: 31.2304, lng: 121.4737 },
    hints: ['Rascacielos', 'Río Huangpu', 'Metrópolis', 'Puerto'],
  },
  {
    id: 'seoul-south-korea',
    name: 'Seúl, Corea del Sur',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=Seoul+South+Korea',
    country: 'Corea del Sur',
    city: 'Seúl',
    continent: 'Asia',
    coordinates: { lat: 37.5665, lng: 126.9780 },
    hints: ['K-pop', 'Capital de Corea del Sur', 'Tecnología', 'Gangnam'],
  },
  {
    id: 'bangkok-thailand',
    name: 'Bangkok, Tailandia',
    imageUrl: 'https://via.placeholder.com/800x600/f39c12/ffffff?text=Bangkok+Thailand',
    country: 'Tailandia',
    city: 'Bangkok',
    continent: 'Asia',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    hints: ['Templos', 'Capital de Tailandia', 'Tuk-tuk', 'Comida callejera'],
  },
  {
    id: 'singapore-singapore',
    name: 'Singapur',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Singapore',
    country: 'Singapur',
    city: 'Singapur',
    continent: 'Asia',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    hints: ['Ciudad-Estado', 'Merlion', 'Multicultural', 'Muy limpia'],
  },
  {
    id: 'mumbai-india',
    name: 'Mumbai, India',
    imageUrl: 'https://via.placeholder.com/800x600/8e44ad/ffffff?text=Mumbai+India',
    country: 'India',
    city: 'Mumbai',
    continent: 'Asia',
    coordinates: { lat: 19.0760, lng: 72.8777 },
    hints: ['Bollywood', 'Puerta de la India', 'Poblada', 'Costa'],
  },
  {
    id: 'delhi-india',
    name: 'Nueva Delhi, India',
    imageUrl: 'https://via.placeholder.com/800x600/d35400/ffffff?text=Delhi+India',
    country: 'India',
    city: 'Nueva Delhi',
    continent: 'Asia',
    coordinates: { lat: 28.6139, lng: 77.2090 },
    hints: ['Capital de India', 'Templo del Loto', 'Histórica', 'Rickshaw'],
  },
  {
    id: 'dubai-uae',
    name: 'Dubái, Emiratos Árabes Unidos',
    imageUrl: 'https://via.placeholder.com/800x600/f1c40f/ffffff?text=Dubai+UAE',
    country: 'Emiratos Árabes Unidos',
    city: 'Dubái',
    continent: 'Asia',
    coordinates: { lat: 25.2048, lng: 55.2708 },
    hints: ['Burj Khalifa', 'Desierto', 'Lujo', 'Islas artificiales'],
  },
  {
    id: 'jerusalem-israel',
    name: 'Jerusalén, Israel',
    imageUrl: 'https://via.placeholder.com/800x600/c0392b/ffffff?text=Jerusalem+Israel',
    country: 'Israel',
    city: 'Jerusalén',
    continent: 'Asia',
    coordinates: { lat: 31.7683, lng: 35.2137 },
    hints: ['Ciudad sagrada', 'Muro de los Lamentos', 'Dome of the Rock', 'Histórica'],
  },
  {
    id: 'tel-aviv-israel',
    name: 'Tel Aviv, Israel',
    imageUrl: 'https://via.placeholder.com/800x600/3498db/ffffff?text=Tel+Aviv+Israel',
    country: 'Israel',
    city: 'Tel Aviv',
    continent: 'Asia',
    coordinates: { lat: 32.0853, lng: 34.7818 },
    hints: ['Mediterráneo', 'Playas', 'Modernista', 'Startups'],
  },
  {
    id: 'kuala-lumpur-malaysia',
    name: 'Kuala Lumpur, Malasia',
    imageUrl: 'https://via.placeholder.com/800x600/16a085/ffffff?text=Kuala+Lumpur+Malaysia',
    country: 'Malasia',
    city: 'Kuala Lumpur',
    continent: 'Asia',
    coordinates: { lat: 3.1390, lng: 101.6869 },
    hints: ['Petronas Towers', 'Capital de Malasia', 'Tropical', 'Multicultural'],
  },
  {
    id: 'jakarta-indonesia',
    name: 'Yakarta, Indonesia',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Jakarta+Indonesia',
    country: 'Indonesia',
    city: 'Yakarta',
    continent: 'Asia',
    coordinates: { lat: -6.2088, lng: 106.8456 },
    hints: ['Capital de Indonesia', 'Poblada', 'Islas', 'Cultura diversa'],
  },
  {
    id: 'manila-philippines',
    name: 'Manila, Filipinas',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=Manila+Philippines',
    country: 'Filipinas',
    city: 'Manila',
    continent: 'Asia',
    coordinates: { lat: 14.5995, lng: 120.9842 },
    hints: ['Capital de Filipinas', 'Océano Pacífico', 'Islas', 'Español'],
  },
  {
    id: 'ho-chi-minh-vietnam',
    name: 'Ho Chi Minh, Vietnam',
    imageUrl: 'https://via.placeholder.com/800x600/34495e/ffffff?text=Ho+Chi+Minh+Vietnam',
    country: 'Vietnam',
    city: 'Ho Chi Minh',
    continent: 'Asia',
    coordinates: { lat: 10.8231, lng: 106.6297 },
    hints: ['Mekong', 'Ciudad antigua', 'Motos', 'Comida vietnamita'],
  },
  {
    id: 'hanoi-vietnam',
    name: 'Hanói, Vietnam',
    imageUrl: 'https://via.placeholder.com/800x600/e67e22/ffffff?text=Hanoi+Vietnam',
    country: 'Vietnam',
    city: 'Hanói',
    continent: 'Asia',
    coordinates: { lat: 21.0285, lng: 105.8542 },
    hints: ['Capital de Vietnam', 'Lago Hoan Kiem', 'Histórica', 'Norte'],
  },
  
  // AMÉRICA
  {
    id: 'new-york-usa',
    name: 'Nueva York, Estados Unidos',
    imageUrl: 'https://via.placeholder.com/800x600/3498db/ffffff?text=New+York+USA',
    country: 'Estados Unidos',
    city: 'Nueva York',
    continent: 'América',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    hints: ['Estatua de la Libertad', 'Times Square', 'Central Park', 'Rascacielos'],
  },
  {
    id: 'los-angeles-usa',
    name: 'Los Ángeles, Estados Unidos',
    imageUrl: 'https://via.placeholder.com/800x600/f39c12/ffffff?text=Los+Angeles+USA',
    country: 'Estados Unidos',
    city: 'Los Ángeles',
    continent: 'América',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    hints: ['Hollywood', 'Playas', 'Océano Pacífico', 'Cine'],
  },
  {
    id: 'chicago-usa',
    name: 'Chicago, Estados Unidos',
    imageUrl: 'https://via.placeholder.com/800x600/2c3e50/ffffff?text=Chicago+USA',
    country: 'Estados Unidos',
    city: 'Chicago',
    continent: 'América',
    coordinates: { lat: 41.8781, lng: -87.6298 },
    hints: ['Vientos', 'Lago Michigan', 'Rascacielos', 'Pizza'],
  },
  {
    id: 'san-francisco-usa',
    name: 'San Francisco, Estados Unidos',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=San+Francisco+USA',
    country: 'Estados Unidos',
    city: 'San Francisco',
    continent: 'América',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    hints: ['Golden Gate', 'Colinas', 'Tecnología', 'Cable cars'],
  },
  {
    id: 'washington-usa',
    name: 'Washington D.C., Estados Unidos',
    imageUrl: 'https://via.placeholder.com/800x600/e74c3c/ffffff?text=Washington+DC+USA',
    country: 'Estados Unidos',
    city: 'Washington D.C.',
    continent: 'América',
    coordinates: { lat: 38.9072, lng: -77.0369 },
    hints: ['Casa Blanca', 'Capital de EE.UU.', 'Monumentos', 'Política'],
  },
  {
    id: 'miami-usa',
    name: 'Miami, Estados Unidos',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Miami+USA',
    country: 'Estados Unidos',
    city: 'Miami',
    continent: 'América',
    coordinates: { lat: 25.7617, lng: -80.1918 },
    hints: ['Playas', 'Art Deco', 'Caribe', 'Caliente'],
  },
  {
    id: 'mexico-city-mexico',
    name: 'Ciudad de México, México',
    imageUrl: 'https://via.placeholder.com/800x600/8e44ad/ffffff?text=Mexico+City+Mexico',
    country: 'México',
    city: 'Ciudad de México',
    continent: 'América',
    coordinates: { lat: 19.4326, lng: -99.1332 },
    hints: ['Capital de México', 'Aztecas', 'Muy poblada', 'Zócalo'],
  },
  {
    id: 'cancun-mexico',
    name: 'Cancún, México',
    imageUrl: 'https://via.placeholder.com/800x600/16a085/ffffff?text=Cancun+Mexico',
    country: 'México',
    city: 'Cancún',
    continent: 'América',
    coordinates: { lat: 21.1619, lng: -86.8515 },
    hints: ['Caribe', 'Playas', 'Turismo', 'Riviera Maya'],
  },
  {
    id: 'rio-brazil',
    name: 'Río de Janeiro, Brasil',
    imageUrl: 'https://via.placeholder.com/800x600/f1c40f/ffffff?text=Rio+de+Janeiro+Brazil',
    country: 'Brasil',
    city: 'Río de Janeiro',
    continent: 'América',
    coordinates: { lat: -22.9068, lng: -43.1729 },
    hints: ['Cristo Redentor', 'Carnaval', 'Copacabana', 'Samba'],
  },
  {
    id: 'sao-paulo-brazil',
    name: 'São Paulo, Brasil',
    imageUrl: 'https://via.placeholder.com/800x600/c0392b/ffffff?text=Sao+Paulo+Brazil',
    country: 'Brasil',
    city: 'São Paulo',
    continent: 'América',
    coordinates: { lat: -23.5505, lng: -46.6333 },
    hints: ['Muy poblada', 'Negocios', 'Diversidad', 'Metrópolis'],
  },
  {
    id: 'buenos-aires-argentina',
    name: 'Buenos Aires, Argentina',
    imageUrl: 'https://via.placeholder.com/800x600/2980b9/ffffff?text=Buenos+Aires+Argentina',
    country: 'Argentina',
    city: 'Buenos Aires',
    continent: 'América',
    coordinates: { lat: -34.6037, lng: -58.3816 },
    hints: ['Tango', 'Capital de Argentina', 'Europa en América', 'Obelisco'],
  },
  {
    id: 'lima-peru',
    name: 'Lima, Perú',
    imageUrl: 'https://via.placeholder.com/800x600/d35400/ffffff?text=Lima+Peru',
    country: 'Perú',
    city: 'Lima',
    continent: 'América',
    coordinates: { lat: -12.0464, lng: -77.0428 },
    hints: ['Capital de Perú', 'Océano Pacífico', 'Gastronomía', 'Histórica'],
  },
  {
    id: 'santiago-chile',
    name: 'Santiago, Chile',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Santiago+Chile',
    country: 'Chile',
    city: 'Santiago',
    continent: 'América',
    coordinates: { lat: -33.4489, lng: -70.6693 },
    hints: ['Andes', 'Capital de Chile', 'Vino', 'Cordillera'],
  },
  {
    id: 'bogota-colombia',
    name: 'Bogotá, Colombia',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=Bogota+Colombia',
    country: 'Colombia',
    city: 'Bogotá',
    continent: 'América',
    coordinates: { lat: 4.7110, lng: -74.0721 },
    hints: ['Capital de Colombia', 'Alta', 'Andes', 'Ciclovía'],
  },
  {
    id: 'caracas-venezuela',
    name: 'Caracas, Venezuela',
    imageUrl: 'https://via.placeholder.com/800x600/34495e/ffffff?text=Caracas+Venezuela',
    country: 'Venezuela',
    city: 'Caracas',
    continent: 'América',
    coordinates: { lat: 10.4806, lng: -66.9036 },
    hints: ['Capital de Venezuela', 'Montañas', 'Caribe', 'Tropical'],
  },
  {
    id: 'montreal-canada',
    name: 'Montreal, Canadá',
    imageUrl: 'https://via.placeholder.com/800x600/e67e22/ffffff?text=Montreal+Canada',
    country: 'Canadá',
    city: 'Montreal',
    continent: 'América',
    coordinates: { lat: 45.5017, lng: -73.5673 },
    hints: ['Francés', 'Quebec', 'Frío', 'Bilingüe'],
  },
  {
    id: 'toronto-canada',
    name: 'Toronto, Canadá',
    imageUrl: 'https://via.placeholder.com/800x600/3498db/ffffff?text=Toronto+Canada',
    country: 'Canadá',
    city: 'Toronto',
    continent: 'América',
    coordinates: { lat: 43.6532, lng: -79.3832 },
    hints: ['CN Tower', 'Lago Ontario', 'Multicultural', 'Frío'],
  },
  {
    id: 'havana-cuba',
    name: 'La Habana, Cuba',
    imageUrl: 'https://via.placeholder.com/800x600/f39c12/ffffff?text=Havana+Cuba',
    country: 'Cuba',
    city: 'La Habana',
    continent: 'América',
    coordinates: { lat: 23.1136, lng: -82.3666 },
    hints: ['Capital de Cuba', 'Caribe', 'Vintage', 'Ron'],
  },
  
  // OCEANÍA
  {
    id: 'sydney-australia',
    name: 'Sídney, Australia',
    imageUrl: 'https://via.placeholder.com/800x600/16a085/ffffff?text=Sydney+Australia',
    country: 'Australia',
    city: 'Sídney',
    continent: 'Oceanía',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    hints: ['Ópera', 'Puente del puerto', 'Canguros', 'Costa'],
  },
  {
    id: 'melbourne-australia',
    name: 'Melbourne, Australia',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Melbourne+Australia',
    country: 'Australia',
    city: 'Melbourne',
    continent: 'Oceanía',
    coordinates: { lat: -37.8136, lng: 144.9631 },
    hints: ['Deportes', 'Cultura', 'Tranvías', 'Cafés'],
  },
  {
    id: 'auckland-new-zealand',
    name: 'Auckland, Nueva Zelanda',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=Auckland+New+Zealand',
    country: 'Nueva Zelanda',
    city: 'Auckland',
    continent: 'Oceanía',
    coordinates: { lat: -36.8485, lng: 174.7633 },
    hints: ['Volcanes', 'Puerto', 'Islas', 'Naturaleza'],
  },
  {
    id: 'wellington-new-zealand',
    name: 'Wellington, Nueva Zelanda',
    imageUrl: 'https://via.placeholder.com/800x600/8e44ad/ffffff?text=Wellington+New+Zealand',
    country: 'Nueva Zelanda',
    city: 'Wellington',
    continent: 'Oceanía',
    coordinates: { lat: -41.2865, lng: 174.7762 },
    hints: ['Capital de Nueva Zelanda', 'Vientos', 'Colinas', 'Cine'],
  },
  
  // ÁFRICA
  {
    id: 'cairo-egypt',
    name: 'El Cairo, Egipto',
    imageUrl: 'https://via.placeholder.com/800x600/f1c40f/ffffff?text=Cairo+Egypt',
    country: 'Egipto',
    city: 'El Cairo',
    continent: 'África',
    coordinates: { lat: 30.0444, lng: 31.2357 },
    hints: ['Pirámides', 'Capital de Egipto', 'Nilo', 'Antigua'],
  },
  {
    id: 'cape-town-south-africa',
    name: 'Ciudad del Cabo, Sudáfrica',
    imageUrl: 'https://via.placeholder.com/800x600/c0392b/ffffff?text=Cape+Town+South+Africa',
    country: 'Sudáfrica',
    city: 'Ciudad del Cabo',
    continent: 'África',
    coordinates: { lat: -33.9249, lng: 18.4241 },
    hints: ['Mesa', 'Océano', 'Vinos', 'Montañas'],
  },
  {
    id: 'johannesburg-south-africa',
    name: 'Johannesburgo, Sudáfrica',
    imageUrl: 'https://via.placeholder.com/800x600/2980b9/ffffff?text=Johannesburg+South+Africa',
    country: 'Sudáfrica',
    city: 'Johannesburgo',
    continent: 'África',
    coordinates: { lat: -26.2041, lng: 28.0473 },
    hints: ['Oro', 'Altitud', 'Negocios', 'Safari'],
  },
  {
    id: 'nairobi-kenya',
    name: 'Nairobi, Kenia',
    imageUrl: 'https://via.placeholder.com/800x600/d35400/ffffff?text=Nairobi+Kenya',
    country: 'Kenia',
    city: 'Nairobi',
    continent: 'África',
    coordinates: { lat: -1.2921, lng: 36.8219 },
    hints: ['Capital de Kenia', 'Safari', 'Equador', 'Altitud'],
  },
  {
    id: 'casablanca-morocco',
    name: 'Casablanca, Marruecos',
    imageUrl: 'https://via.placeholder.com/800x600/27ae60/ffffff?text=Casablanca+Morocco',
    country: 'Marruecos',
    city: 'Casablanca',
    continent: 'África',
    coordinates: { lat: 33.5731, lng: -7.5898 },
    hints: ['Atlas', 'Mediterráneo', 'Cine', 'Puerto'],
  },
  {
    id: 'marrakech-morocco',
    name: 'Marrakech, Marruecos',
    imageUrl: 'https://via.placeholder.com/800x600/9b59b6/ffffff?text=Marrakech+Morocco',
    country: 'Marruecos',
    city: 'Marrakech',
    continent: 'África',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    hints: ['Souk', 'Medina', 'Desierto', 'Colorida'],
  },
  {
    id: 'lagos-nigeria',
    name: 'Lagos, Nigeria',
    imageUrl: 'https://via.placeholder.com/800x600/34495e/ffffff?text=Lagos+Nigeria',
    country: 'Nigeria',
    city: 'Lagos',
    continent: 'África',
    coordinates: { lat: 6.5244, lng: 3.3792 },
    hints: ['Poblada', 'Costa', 'Negocios', 'Tropical'],
  },
  {
    id: 'tunis-tunisia',
    name: 'Túnez, Túnez',
    imageUrl: 'https://via.placeholder.com/800x600/e67e22/ffffff?text=Tunis+Tunisia',
    country: 'Túnez',
    city: 'Túnez',
    continent: 'África',
    coordinates: { lat: 36.8065, lng: 10.1815 },
    hints: ['Capital de Túnez', 'Mediterráneo', 'Histórica', 'Árabe'],
  },
];

// Función para obtener una ubicación aleatoria
export const getRandomLocation = (gameMode = 'country') => {
  const locations = LOCATIONS;
  const randomIndex = Math.floor(Math.random() * locations.length);
  return locations[randomIndex];
};

// Función para obtener ubicaciones por país
export const getLocationsByCountry = (country) => {
  return LOCATIONS.filter(loc => loc.country === country);
};

// Función para obtener ubicaciones por continente
export const getLocationsByContinent = (continent) => {
  return LOCATIONS.filter(loc => loc.continent === continent);
};

// Función para obtener todas las ubicaciones de un continente específico
export const getContinents = () => {
  const continents = [...new Set(LOCATIONS.map(loc => loc.continent))];
  return continents.sort();
};

// Función para obtener países únicos
export const getCountries = () => {
  const countries = [...new Set(LOCATIONS.map(loc => loc.country))];
  return countries.sort();
};

// Función para obtener pistas de una ubicación
export const getLocationHints = (locationId) => {
  const location = LOCATIONS.find(loc => loc.id === locationId);
  return location?.hints || [];
};

